import { ScenarioDefinition } from './types';
import { PumpInputs } from '../types/pump';
import { RotorInputs } from '../types/rotor';
import { PipeInputs } from '../types/pipe';
import { SealInputs } from '../types/seal';
import { AlignmentInputs } from '../types/alignment';

// ==========================================
// 1. PUMP CAVITATION SCENARIOS
// ==========================================
export const PUMP_SCENARIOS: (ScenarioDefinition<PumpInputs> & { name: string; inputs: PumpInputs })[] = [
  {
    id: 'optimal-flooded',
    name: 'Normal Operation (Flooded Suction)',
    label: 'Normal Operation (Flooded Suction)',
    simulator: 'pump',
    category: 'normal',
    event: 'Normal flooded supply established.',
    consequence: 'NPSH margin is safe and within guideline envelope.',
    recommendedAction: 'Maintain current steady-state operational parameters.',
    description: 'Normal flooded intake with generous NPSH margin.',
    events: [
      'Normal flooded supply established.',
      'NPSH margin is safe and within guideline envelope.',
    ],
    insight: 'Safe hydraulic operating envelope with zero vapor bubble formation.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'flooded_suction',
      staticHeadM: 3.5,
      tankPressureKPag: 0,
      pipeDiameterMm: 150,
      pipeLengthM: 8,
      pipeRoughnessMm: 0.045,
      flowRateM3h: 120,
      bepFlowM3h: 130,
      ratedHeadM: 60,
      shutOffHeadM: 72,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 130,
      npshrInputMode: 'single_value',
      npshr3percentM: 2.8,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 150,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      safetyMarginType: 'normal',
      atmosphericPressureKPa: 101.325,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 1,
        teeBranchFlow: 0,
        entranceLoss: 'radiused',
      },
    },
  },
  {
    id: 'low-suction-level',
    name: 'Low Suction Level',
    label: 'Low Suction Level',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Tank level dropped.',
    consequence: 'NPSH margin decreased.',
    recommendedAction: 'Increase suction level or reduce flow.',
    description: 'Liquid level drops to critical suction lift.',
    events: [
      'Tank level dropped.',
      'NPSH margin decreased.',
    ],
    insight: 'Suction lift reduces NPSHa below allowable safety margin.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 22,
      suctionSourceType: 'suction_lift',
      staticHeadM: -3.8,
      tankPressureKPag: 0,
      pipeDiameterMm: 100,
      pipeLengthM: 12,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 85,
      bepFlowM3h: 85,
      ratedHeadM: 50,
      shutOffHeadM: 60,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 105,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.2,
      foulingFactor: 1.1,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pipeDiameterChangeMm: 100,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'normal',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 1,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
    },
  },
  {
    id: 'high-temperature',
    name: 'High Temperature',
    label: 'High Temperature',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Process fluid temperature spiked to 95°C.',
    consequence: 'Vapor pressure increased sharply, causing cavitation.',
    recommendedAction: 'Cool suction fluid or increase vessel pressure.',
    description: 'Hot condensate near boiling point with elevated vapor pressure.',
    events: [
      'Process fluid temperature spiked to 95°C.',
      'Vapor pressure increased sharply, causing cavitation.',
    ],
    insight: 'Elevated vapor pressure erodes available NPSH margin.',
    inputs: {
      fluidId: 'boiler_feed',
      fluidTempC: 95,
      suctionSourceType: 'pressurized_vessel',
      tankPressureKPag: 12,
      staticHeadM: 1.8,
      pipeDiameterMm: 125,
      pipeLengthM: 14,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 110,
      bepFlowM3h: 120,
      ratedHeadM: 110,
      shutOffHeadM: 135,
      pumpSpeedRpm: 2950,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.5,
      foulingFactor: 1.15,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pipeDiameterChangeMm: 125,
      pumpType: 'overhung_oh2',
      serviceStandard: 'api610',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'conservative',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
    },
  },
  {
    id: 'blocked-strainer',
    name: 'Blocked Strainer',
    label: 'Blocked Strainer',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Suction strainer clogged with debris.',
    consequence: 'Frictional head loss surged, starving pump suction.',
    recommendedAction: 'Clean or swap suction strainer basket.',
    description: 'Heavy particulate fouling in suction strainer basket.',
    events: [
      'Suction strainer clogged with debris.',
      'Frictional head loss surged, starving pump suction.',
    ],
    insight: 'Severe minor head loss across fouled strainer starves impeller inlet.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 25,
      suctionSourceType: 'flooded_suction',
      staticHeadM: 1.5,
      tankPressureKPag: 0,
      pipeDiameterMm: 125,
      pipeLengthM: 10,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 100,
      bepFlowM3h: 100,
      ratedHeadM: 55,
      shutOffHeadM: 68,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.0,
      foulingFactor: 3.5,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pipeDiameterChangeMm: 125,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'normal',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 5,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
    },
  },
  {
    id: 'throttled-suction-valve',
    name: 'Throttled Suction Valve',
    label: 'Throttled Suction Valve',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Suction isolation valve throttled to 20% open.',
    consequence: 'Severe localized pressure drop triggered cavitation.',
    recommendedAction: 'Fully open suction valve and control flow at discharge.',
    description: 'Restricted suction valve creating localized vacuum and vortexing.',
    events: [
      'Suction isolation valve throttled to 20% open.',
      'Severe localized pressure drop triggered cavitation.',
    ],
    insight: 'Throttling pump suction creates steep pressure drop and acoustic cavitation.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 25,
      suctionSourceType: 'flooded_suction',
      staticHeadM: 2.0,
      tankPressureKPag: 0,
      pipeDiameterMm: 125,
      pipeLengthM: 10,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 100,
      bepFlowM3h: 100,
      ratedHeadM: 55,
      shutOffHeadM: 68,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.0,
      foulingFactor: 1.0,
      valveOpeningPercent: 20,
      gasEntrainmentPercent: 0,
      pipeDiameterChangeMm: 125,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'normal',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
    },
  },
  {
    id: 'gas-entrainment',
    name: 'Gas Entrainment',
    label: 'Gas Entrainment',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Free air or gas entrained into suction line.',
    consequence: 'Vapor pockets formed in impeller, causing surging.',
    recommendedAction: 'Eliminate sump vortexing and vent suction pipe.',
    description: 'Air entrainment or vortexing in suction line inducing head degradation.',
    events: [
      'Free air or gas entrained into suction line.',
      'Vapor pockets formed in impeller, causing surging.',
    ],
    insight: 'Gas entrainment separates flow from impeller vanes, causing air binding.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 25,
      suctionSourceType: 'flooded_suction',
      staticHeadM: 1.5,
      tankPressureKPag: 0,
      pipeDiameterMm: 125,
      pipeLengthM: 10,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 100,
      bepFlowM3h: 100,
      ratedHeadM: 55,
      shutOffHeadM: 68,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.0,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 8,
      pipeDiameterChangeMm: 125,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'normal',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'reentrant',
      },
    },
  },
  {
    id: 'pump-trip',
    name: 'Pump Trip',
    label: 'Pump Trip',
    simulator: 'pump',
    category: 'abnormal',
    event: 'Pump motor power tripped; shaft speed decelerating.',
    consequence: 'Flow collapsed to zero with transient pressure surge.',
    recommendedAction: 'Verify trip cause, check check valve, and restart.',
    description: 'Sudden electrical trip causing rapid hydraulic deceleration.',
    events: [
      'Pump motor power tripped; shaft speed decelerating.',
      'Flow collapsed to zero with transient pressure surge.',
    ],
    insight: 'Immediate loss of driving head; discharge line check valve seating check required.',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'flooded_suction',
      staticHeadM: 1.5,
      tankPressureKPag: 0,
      pipeDiameterMm: 125,
      pipeLengthM: 10,
      pipeRoughnessMm: 0.05,
      flowRateM3h: 0,
      bepFlowM3h: 100,
      ratedHeadM: 0,
      shutOffHeadM: 0,
      pumpSpeedRpm: 0,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 0,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pipeDiameterChangeMm: 125,
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
      atmosphericPressureKPa: 101.325,
      safetyMarginType: 'normal',
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
    },
  },
];

// ==========================================
// 2. ROTOR UNBALANCE SCENARIOS
// ==========================================
export const ROTOR_SCENARIOS: (ScenarioDefinition<RotorInputs> & { name: string; inputs: RotorInputs })[] = [
  {
    id: 'iso-g25-balanced',
    name: 'Precision Balanced (ISO G2.5 Baseline)',
    label: 'Precision Balanced (ISO G2.5 Baseline)',
    simulator: 'rotor',
    category: 'normal',
    event: 'Precision dynamic balancing confirmed.',
    consequence: 'Vibration RMS < 1.2 mm/s (ISO 10816 Zone A), bearing life > 100,000 hrs.',
    recommendedAction: 'Maintain standard condition monitoring and lubrication intervals.',
    description: 'Precision balanced rotor operating in ISO Zone A with long bearing life.',
    events: [
      'Precision dynamic balancing confirmed.',
      'Vibration RMS < 1.2 mm/s (ISO 10816 Zone A), bearing life > 100,000 hrs.',
    ],
    insight: 'Optimal dynamic balance: calculated L10mh bearing rating life exceeds 100,000 hrs.',
    inputs: {
      rotorMassKg: 80,
      operatingRpm: 1800,
      unbalanceMassGrams: 0.8,
      unbalanceRadiusMm: 120,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 6.5,
      staticRadialLoadN: 700,
      axialLoadN: 150,
      lubricationCondition: 'good',
      contaminationLevel: 'clean',
      reliabilityTarget: 0.90,
      machineType: 'motor',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 60,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 600,
      overhungLengthMm: 150,
      loadDistributionFactor: 0.55,
    },
  },
  {
    id: 'heavy-unbalance',
    name: 'Heavy Unbalance',
    label: 'Heavy Unbalance',
    simulator: 'rotor',
    category: 'abnormal',
    event: 'Large mass unbalance added to rotor plane.',
    consequence: '1X vibration surged past ISO Zone D trip limit.',
    recommendedAction: 'Stop unit and perform dynamic trim balancing.',
    description: 'Heavy residual unbalance generating massive 1X centrifugal load.',
    events: [
      'Large mass unbalance added to rotor plane.',
      '1X vibration surged past ISO Zone D trip limit.',
    ],
    insight: 'Severe unbalance generates excessive cyclic fatigue, reducing bearing life to < 2,500 hrs.',
    inputs: {
      rotorMassKg: 120,
      operatingRpm: 2950,
      unbalanceMassGrams: 45.0,
      unbalanceRadiusMm: 200,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingModelId: '6312',
      basicDynamicLoadC_kN: 82,
      useDirectLoadP: true,
      equivalentLoadP_kN: 24.0,
      staticRadialLoadN: 1200,
      axialLoadN: 300,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 50,
      dampingRatio: 0.04,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 700,
      overhungLengthMm: 180,
      loadDistributionFactor: 0.60,
    },
  },
  {
    id: 'blade-loss',
    name: 'Blade Loss',
    label: 'Blade Loss',
    simulator: 'rotor',
    category: 'abnormal',
    event: 'Sudden impeller blade or fan vane breakage.',
    consequence: 'Extreme centrifugal force and violent shaft whirl.',
    recommendedAction: 'Emergency trip machine and inspect rotating assembly.',
    description: 'Sudden blade detachment causing major unbalance asymmetry.',
    events: [
      'Sudden impeller blade or fan vane breakage.',
      'Extreme centrifugal force and violent shaft whirl.',
    ],
    insight: 'Severe mass asymmetry causes shaft whirl and structural trip alarm.',
    inputs: {
      rotorMassKg: 120,
      operatingRpm: 3000,
      unbalanceMassGrams: 120.0,
      unbalanceRadiusMm: 250,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingModelId: '6312',
      basicDynamicLoadC_kN: 82,
      useDirectLoadP: true,
      equivalentLoadP_kN: 42.0,
      staticRadialLoadN: 1200,
      axialLoadN: 300,
      lubricationCondition: 'poor',
      contaminationLevel: 'contaminated',
      reliabilityTarget: 0.90,
      machineType: 'fan',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 45,
      dampingRatio: 0.03,
      bearingPosition: 'overhung',
      bearingSpanMm: 650,
      overhungLengthMm: 220,
      loadDistributionFactor: 0.75,
    },
  },
  {
    id: 'near-critical-speed',
    name: 'Near Critical Speed',
    label: 'Near Critical Speed',
    simulator: 'rotor',
    category: 'abnormal',
    event: 'Operating speed shifted into 1st critical resonance zone.',
    consequence: 'Vibration amplified by resonance; orbit expanded.',
    recommendedAction: 'Shift operating RPM out of critical speed lockout band.',
    description: 'Operating speed matching lateral natural frequency (resonance amplification).',
    events: [
      'Operating speed shifted into 1st critical resonance zone.',
      'Vibration amplified by resonance; orbit expanded.',
    ],
    insight: 'Resonance separation margin violated (<20% from 1st lateral critical speed).',
    inputs: {
      rotorMassKg: 150,
      operatingRpm: 2150,
      unbalanceMassGrams: 8.0,
      unbalanceRadiusMm: 160,
      balanceGrade: 'G2.5',
      rotorStiffnessKNmm: 35,
      dampingRatio: 0.04,
      bearingType: 'ball',
      bearingModelId: '6312',
      basicDynamicLoadC_kN: 82,
      useDirectLoadP: true,
      equivalentLoadP_kN: 14.0,
      staticRadialLoadN: 1500,
      axialLoadN: 200,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'motor',
      machineClass: 'class_2_medium',
      bearingPosition: 'between_bearings',
      bearingSpanMm: 800,
      overhungLengthMm: 160,
      loadDistributionFactor: 0.55,
    },
  },
  {
    id: 'lubrication-loss',
    name: 'Lubrication Loss',
    label: 'Lubrication Loss',
    simulator: 'rotor',
    category: 'abnormal',
    event: 'Bearing oil supply failed or grease degraded.',
    consequence: 'Film collapsed into boundary friction; bearing life < 100 hrs.',
    recommendedAction: 'Restore lubricant flow and flush bearing housing.',
    description: 'Loss of hydrodynamic oil film leading to metallic contact.',
    events: [
      'Bearing oil supply failed or grease degraded.',
      'Film collapsed into boundary friction; bearing life < 100 hrs.',
    ],
    insight: 'Viscosity ratio κ dropped below boundary threshold; life factor a_ISO penalized by 90%.',
    inputs: {
      rotorMassKg: 100,
      operatingRpm: 2950,
      unbalanceMassGrams: 4.0,
      unbalanceRadiusMm: 120,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 12.0,
      staticRadialLoadN: 900,
      axialLoadN: 150,
      lubricationCondition: 'poor',
      contaminationLevel: 'contaminated',
      bearingOperatingTempC: 95,
      reliabilityTarget: 0.95,
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 55,
      dampingRatio: 0.04,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 600,
      overhungLengthMm: 150,
      loadDistributionFactor: 0.55,
    },
  },
  {
    id: 'bearing-overload',
    name: 'Bearing Overload',
    label: 'Bearing Overload',
    simulator: 'rotor',
    category: 'abnormal',
    event: 'Excess radial dynamic load applied to bearing.',
    consequence: 'C/P ratio dropped below 1.5; fatigue failure imminent.',
    recommendedAction: 'Reduce belt tension or rebalance hydraulic thrust.',
    description: 'Extreme external radial load driving equivalent dynamic load P near capacity C.',
    events: [
      'Excess radial dynamic load applied to bearing.',
      'C/P ratio dropped below 1.5; fatigue failure imminent.',
    ],
    inputs: {
      rotorMassKg: 120,
      operatingRpm: 2950,
      unbalanceMassGrams: 10.0,
      unbalanceRadiusMm: 150,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 40,
      useDirectLoadP: true,
      equivalentLoadP_kN: 38.0,
      staticRadialLoadN: 35000,
      axialLoadN: 4000,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'compressor',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 60,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 650,
      overhungLengthMm: 150,
      loadDistributionFactor: 0.60,
    },
  },
];

// ==========================================
// 3. PIPE STRESS SCENARIOS
// ==========================================
export const PIPE_SCENARIOS: (ScenarioDefinition<PipeInputs> & { name: string; inputs: PipeInputs })[] = [
  {
    id: 'adequate-expansion-loop',
    name: 'Flexible Expansion Loop (Baseline)',
    label: 'Flexible Expansion Loop (Baseline)',
    simulator: 'pipe',
    category: 'normal',
    event: 'Expansion U-loop geometry active.',
    consequence: 'Thermal growth absorbed safely within ASME B31.3 limits.',
    recommendedAction: 'Ensure axial pipe guides are spaced per standard span tables.',
    description: 'Symmetrical expansion U-loop absorbing thermal expansion with safe stress ratio.',
    events: [
      'Expansion U-loop geometry active.',
      'Thermal growth absorbed safely within ASME B31.3 limits.',
    ],
    insight: 'Guided cantilever flexibility lowers anchor nozzle reaction force to < 8.5 kN.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 35.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 220,
      operatingPressureBar: 16,
      anchorCondition: 'expansion_loop',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 15,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.0,
      expansionLoopWidthM: 3.5,
      expansionLoopHeightM: 4.5,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 10.0,
    },
  },
  {
    id: 'failed-anchor',
    name: 'Failed Anchor',
    label: 'Failed Anchor',
    simulator: 'pipe',
    category: 'abnormal',
    event: 'Terminal fixed anchor slipped and lost rigidity.',
    consequence: 'Thermal growth displaced piping onto adjacent structure.',
    recommendedAction: 'Re-anchor support structure and reinforce base plate.',
    description: 'Anchor failure allowing uncontrolled axial displacement and bending.',
    events: [
      'Terminal fixed anchor slipped and lost rigidity.',
      'Thermal growth displaced piping onto adjacent structure.',
    ],
    insight: 'Loss of anchor rigidity transfers thermal thrust onto adjacent equipment nozzles.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 30.0,
      pipeOuterDiameterMm: 219.1,
      pipeWallThicknessMm: 8.18,
      installationTempC: 20,
      operatingTempC: 320,
      operatingPressureBar: 18,
      anchorCondition: 'one_end_fixed_one_end_free',
      constraintFactorType: 'free_expansion',
      restraintPercent: 0,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.0,
      expansionLoopWidthM: 0,
      expansionLoopHeightM: 0,
      numberOfBends: 0,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 10.0,
      isAnchorFailed: true,
    },
  },
  {
    id: 'failed-support',
    name: 'Failed Support',
    label: 'Failed Support',
    simulator: 'pipe',
    category: 'abnormal',
    event: 'Intermediate pipe hanger/guide collapsed.',
    consequence: 'Unsupported span sagged, raising bending stress.',
    recommendedAction: 'Replace failed spring hanger and re-level pipe.',
    description: 'Mid-span hanger/guide structural failure creating excessive sag.',
    events: [
      'Intermediate pipe hanger/guide collapsed.',
      'Unsupported span sagged, raising bending stress.',
    ],
    insight: 'Doubled unsupported span elevates sustained weight bending stress past allowable limit.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 35.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 280,
      operatingPressureBar: 14,
      anchorCondition: 'guided',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 60,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.0,
      expansionLoopWidthM: 0,
      expansionLoopHeightM: 0,
      numberOfBends: 0,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 10.0,
      isSupportFailed: true,
    },
  },
  {
    id: 'thermal-shock',
    name: 'Thermal Shock',
    label: 'Thermal Shock',
    simulator: 'pipe',
    category: 'abnormal',
    event: 'Sudden high-temperature fluid injected into line (+430°C ΔT).',
    consequence: 'Rapid expansion generated transient thermal shock stress.',
    recommendedAction: 'Reduce warm-up ramp rate and add expansion loops.',
    description: 'Rapid temperature step creating high thermal gradient stress.',
    events: [
      'Sudden high-temperature fluid injected into line (+430°C ΔT).',
      'Rapid expansion generated transient thermal shock stress.',
    ],
    insight: 'Instantaneous temperature jump creates steep transient thermal stress.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 25.0,
      pipeOuterDiameterMm: 219.1,
      pipeWallThicknessMm: 8.18,
      installationTempC: 20,
      operatingTempC: 450,
      operatingPressureBar: 22,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 95,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.5,
      allowableStressMPa: 125.0,
      expansionLoopWidthM: 0,
      expansionLoopHeightM: 0,
      numberOfBends: 0,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 10.0,
      isThermalShock: true,
    },
  },
  {
    id: 'fully-restrained-pipe',
    name: 'Fully Restrained Pipe',
    label: 'Fully Restrained Pipe',
    simulator: 'pipe',
    category: 'abnormal',
    event: 'Pipe line fully locked between rigid bulkheads.',
    consequence: 'Thermal stress exceeded ASME allowable limit by >300%.',
    recommendedAction: 'Add expansion loops or flexible directional offsets.',
    description: 'Straight carbon steel run fully restrained between rigid anchor bulkheads.',
    events: [
      'Pipe line fully locked between rigid bulkheads.',
      'Thermal stress exceeded ASME allowable limit by >300%.',
    ],
    insight: 'Rigid constraints generate >800 MPa compressive thermal stress.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 20.0,
      pipeOuterDiameterMm: 219.1,
      pipeWallThicknessMm: 8.18,
      installationTempC: 20,
      operatingTempC: 380,
      operatingPressureBar: 20,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 100,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.0,
      expansionLoopWidthM: 0,
      expansionLoopHeightM: 0,
      numberOfBends: 0,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 10.0,
    },
  },
  {
    id: 'nozzle-overload',
    name: 'Nozzle Overload',
    label: 'Nozzle Overload',
    simulator: 'pipe',
    category: 'abnormal',
    event: 'Excessive thermal thrust transmitted to pump nozzle.',
    consequence: 'API 610 allowable nozzle load exceeded, risking casing distortion.',
    recommendedAction: 'Add directional guides or flexible loops to unload nozzle.',
    description: 'Piping thermal growth acting directly against pump casing flange.',
    events: [
      'Excessive thermal thrust transmitted to pump nozzle.',
      'API 610 allowable nozzle load exceeded, risking casing distortion.',
    ],
    insight: 'Thermal anchor reaction exceeds API 610 Table 5 allowable nozzle load limits.',
    inputs: {
      materialType: 'carbon_steel',
      pipeLengthM: 22.0,
      pipeOuterDiameterMm: 219.1,
      pipeWallThicknessMm: 8.18,
      installationTempC: 20,
      operatingTempC: 350,
      operatingPressureBar: 16,
      anchorCondition: 'guided',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 90,
      modulusOfElasticityGPa: 200,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.0,
      expansionLoopWidthM: 0,
      expansionLoopHeightM: 0,
      numberOfBends: 0,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 12.0,
      isNozzleOverloadScenario: true,
    },
  },
];

// ==========================================
// 4. SEAL FLUSH PLAN SCENARIOS
// ==========================================
export const SEAL_SCENARIOS: (ScenarioDefinition<SealInputs> & { name: string; inputs: SealInputs })[] = [
  {
    id: 'plan11-standard-flush',
    name: 'Plan 11 Standard Flush (Baseline)',
    label: 'Plan 11 Standard Flush (Baseline)',
    simulator: 'seal',
    category: 'normal',
    event: 'Plan 11 bypass flush flowing across orifice.',
    consequence: 'Seal face friction heat dissipated; vapor margin sufficient.',
    recommendedAction: 'Monitor flush pipe skin temperature for continuous flow.',
    description: 'Standard discharge bypass flush through restriction orifice into seal chamber.',
    events: [
      'Plan 11 bypass flush flowing across orifice.',
      'Seal face friction heat dissipated; vapor margin sufficient.',
    ],
    insight: 'Stable hydrodynamic face lubrication regime with adequate vapor pressure suppression.',
    inputs: {
      planId: 'plan_11',
      sealSizeMm: 65,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 400,
      pumpDischargePressureKPag: 1200,
      pumpSuctionPressureKPag: 200,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 45,
      processFluidType: 'water',
      fluidDensityKgM3: 990,
      fluidSpecificHeatCp: 4.18,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.05,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5.0,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.2,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
  },
  {
    id: 'cooler-failure',
    name: 'Cooler Failure',
    label: 'Cooler Failure',
    simulator: 'seal',
    category: 'abnormal',
    event: 'Plan 23 seal cooler lost cooling water flow.',
    consequence: 'Chamber temperature rose, degrading elastomer O-rings.',
    recommendedAction: 'Restore cooling water flow and vent cooler air pockets.',
    description: 'Loss of cooling water in Plan 23/21 heat exchanger.',
    events: [
      'Plan 23 seal cooler lost cooling water flow.',
      'Chamber temperature rose, degrading elastomer O-rings.',
    ],
    insight: 'Seal chamber temperature escalates toward uncooled process temperature.',
    inputs: {
      planId: 'plan_23',
      sealSizeMm: 75,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 1800,
      pumpDischargePressureKPag: 3500,
      pumpSuctionPressureKPag: 800,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 160,
      processFluidType: 'boiler_feedwater',
      fluidDensityKgM3: 910,
      fluidSpecificHeatCp: 4.35,
      faceMaterials: 'sic_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.06,
      allowableFlushTempRiseC: 6,
      coolingWaterSupplyTempC: 30,
      coolingWaterFlowLpm: 0,
      coolerCapacityKW: 0,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.2,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
  },
  {
    id: 'barrier-pressure-low',
    name: 'Barrier Pressure Low',
    label: 'Barrier Pressure Low',
    simulator: 'seal',
    category: 'abnormal',
    event: 'Plan 53A barrier reservoir lost nitrogen pressure.',
    consequence: 'Barrier pressure dropped below chamber, reversing differential.',
    recommendedAction: 'Repressurize nitrogen blanket above seal chamber pressure.',
    description: 'Loss of nitrogen pressure blanket in Plan 53A barrier system.',
    events: [
      'Plan 53A barrier reservoir lost nitrogen pressure.',
      'Barrier pressure dropped below chamber, reversing differential.',
    ],
    insight: 'Reversed differential pressure causes process fluid to penetrate barrier loop.',
    inputs: {
      planId: 'plan_53a',
      sealSizeMm: 60,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 650,
      pumpDischargePressureKPag: 1400,
      pumpSuctionPressureKPag: 300,
      barrierBufferPressureKPag: 350,
      processFluidTempC: 60,
      processFluidType: 'hot_hydrocarbon',
      fluidDensityKgM3: 820,
      fluidSpecificHeatCp: 2.15,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      faceMaterials: 'sic_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.05,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5.0,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.2,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'nitrogen',
    },
  },
  {
    id: 'flush-blocked',
    name: 'Flush Blocked',
    label: 'Flush Blocked',
    simulator: 'seal',
    category: 'abnormal',
    event: 'Plan 11 flush line orifice clogged with particulate.',
    consequence: 'Flush flow stopped; friction heat vaporized face film.',
    recommendedAction: 'Clear flush orifice and inspect throat bushing.',
    description: 'Restriction orifice blocked with pipe scale or particulate.',
    events: [
      'Plan 11 flush line orifice clogged with particulate.',
      'Flush flow stopped; friction heat vaporized face film.',
    ],
    insight: 'Flush flow starvation leads to rapid face heating and fluid flashing.',
    inputs: {
      planId: 'plan_11',
      sealSizeMm: 65,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 300,
      pumpDischargePressureKPag: 1100,
      pumpSuctionPressureKPag: 150,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 85,
      processFluidType: 'water',
      fluidDensityKgM3: 970,
      fluidSpecificHeatCp: 4.20,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.06,
      flushOrificeDiameterMm: 0.5,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5.0,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
  },
  {
    id: 'high-temperature',
    name: 'High Temperature',
    label: 'High Temperature',
    simulator: 'seal',
    category: 'abnormal',
    event: 'Process fluid temperature exceeded seal material rating.',
    consequence: 'Seal face fluid flashed into vapor (dry running risk).',
    recommendedAction: 'Increase flush flow or switch to cooled Plan 21/23.',
    description: 'Uncooled hot process fluid causing vapor pressure margin collapse.',
    events: [
      'Process fluid temperature exceeded seal material rating.',
      'Seal face fluid flashed into vapor (dry running risk).',
    ],
    insight: 'Fluid vaporization between seal faces destroys lubricating fluid film.',
    inputs: {
      planId: 'plan_11',
      sealSizeMm: 65,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 400,
      pumpDischargePressureKPag: 1200,
      pumpSuctionPressureKPag: 200,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 135,
      processFluidType: 'water',
      fluidDensityKgM3: 930,
      fluidSpecificHeatCp: 4.28,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.07,
      flushOrificeDiameterMm: 3.2,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5.0,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
  },
  {
    id: 'dry-running-risk',
    name: 'Dry Running Risk',
    label: 'Dry Running Risk',
    simulator: 'seal',
    category: 'abnormal',
    event: 'Seal chamber lost liquid prime during operation.',
    consequence: 'Seal faces running dry with rapid carbon face wear.',
    recommendedAction: 'Vent seal chamber before startup and establish flush flow.',
    description: 'Loss of seal chamber liquid prime or gas-locking condition.',
    events: [
      'Seal chamber lost liquid prime during operation.',
      'Seal faces running dry with rapid carbon face wear.',
    ],
    insight: 'Dry face friction coefficient spikes, generating extreme thermal face blistering.',
    inputs: {
      planId: 'plan_11',
      sealSizeMm: 65,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 50,
      pumpDischargePressureKPag: 100,
      pumpSuctionPressureKPag: 0,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 98,
      processFluidType: 'water',
      fluidDensityKgM3: 960,
      fluidSpecificHeatCp: 4.21,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.15,
      flushOrificeDiameterMm: 1.0,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5.0,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 450,
      pressureControlMethod: 'fixed_n2_regulator',
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
  },
];

// ==========================================
// 5. SHAFT ALIGNMENT & COUPLING SCENARIOS
// ==========================================
export const ALIGNMENT_SCENARIOS: (ScenarioDefinition<AlignmentInputs> & { name: string; inputs: AlignmentInputs })[] = [
  {
    id: 'api686-normal',
    name: 'Normal Operation (Cold Target Aligned)',
    label: 'Normal Operation (Cold Target Aligned)',
    simulator: 'alignment' as any,
    category: 'normal',
    event: 'Cold target offsets calculated and set before startup.',
    consequence: 'Thermal expansion brings machine train to coaxial running state.',
    recommendedAction: 'Verify vibration levels during operating thermal equilibrium.',
    description: 'Precision alignment according to API 686 Chapter 7 protocol.',
    events: [
      'Cold target offsets calculated and set before startup.',
      'Thermal expansion brings machine train to coaxial running state.',
    ],
    insight: 'Intentional cold vertical offset (-0.11 mm) compensates for pump fluid heating.',
    inputs: {
      motorRpm: 2950,
      couplingSpacerLengthMm: 140,
      couplingHubDiameterMm: 160,
      distCouplingToMotorFrontFootMm: 220,
      distMotorFrontToRearFootMm: 380,
      distCouplingToPumpFrontFootMm: 200,
      distPumpFrontToRearFootMm: 320,
      motorCenterlineHeightMm: 280,
      pumpCenterlineHeightMm: 280,
      ambientInstallationTempC: 20,
      motorOperatingTempC: 65,
      pumpFluidTempC: 85,
      pumpCasingMaterial: 'carbon_steel',
      thermalGrowthMode: 'auto_calculated',
      manualTargetVerticalOffsetMm: 0,
      manualTargetAngularOffsetMrad: 0,
      measurementMethod: 'dual_laser',
      measuredVerticalOffsetMm: -0.11,
      measuredVerticalAngleMrad: -0.15,
      measuredHorizontalOffsetMm: 0.02,
      measuredHorizontalAngleMrad: 0.04,
      indicatorBracketSagMm: 0.03,
      softFootFrontLeftMm: 0.02,
      softFootFrontRightMm: 0.03,
      softFootRearLeftMm: 0.02,
      softFootRearRightMm: 0.03,
      couplingType: 'metallic_disc_pack',
      angularStiffnessNmPerMrad: 450,
      radialStiffnessNPerMm: 1800,
      maxAllowableContinuousAngleDeg: 0.5,
      pipingInducedNozzleMomentKnm: 0.2,
    },
  },
  {
    id: 'thermal-offset-neglected',
    name: 'Thermal Growth Neglected (Hot Misalignment)',
    label: 'Thermal Growth Neglected (Hot Misalignment)',
    simulator: 'alignment' as any,
    category: 'abnormal',
    event: 'Machine aligned cold to zero offset without thermal compensation.',
    consequence: 'Hot pump expansion forces shafts out of tolerance (Zone D vibration).',
    recommendedAction: 'Re-align motor lower to accommodate +0.32 mm pump thermal lift.',
    description: 'Hot process fluid (155°C) creates vertical expansion mismatch.',
    events: [
      'Machine aligned cold to zero offset without thermal compensation.',
      'Hot pump expansion forces shafts out of tolerance (Zone D vibration).',
    ],
    insight: 'Pump centerline rises relative to cooler electric motor, violating API 686.',
    inputs: {
      motorRpm: 2950,
      couplingSpacerLengthMm: 140,
      couplingHubDiameterMm: 160,
      distCouplingToMotorFrontFootMm: 220,
      distMotorFrontToRearFootMm: 380,
      distCouplingToPumpFrontFootMm: 200,
      distPumpFrontToRearFootMm: 320,
      motorCenterlineHeightMm: 280,
      pumpCenterlineHeightMm: 280,
      ambientInstallationTempC: 20,
      motorOperatingTempC: 60,
      pumpFluidTempC: 155,
      pumpCasingMaterial: 'carbon_steel',
      thermalGrowthMode: 'auto_calculated',
      manualTargetVerticalOffsetMm: 0,
      manualTargetAngularOffsetMrad: 0,
      measurementMethod: 'dual_laser',
      measuredVerticalOffsetMm: 0.02,
      measuredVerticalAngleMrad: 0.03,
      measuredHorizontalOffsetMm: 0.02,
      measuredHorizontalAngleMrad: 0.04,
      indicatorBracketSagMm: 0.03,
      softFootFrontLeftMm: 0.02,
      softFootFrontRightMm: 0.03,
      softFootRearLeftMm: 0.02,
      softFootRearRightMm: 0.03,
      couplingType: 'metallic_disc_pack',
      angularStiffnessNmPerMrad: 450,
      radialStiffnessNPerMm: 1800,
      maxAllowableContinuousAngleDeg: 0.5,
      pipingInducedNozzleMomentKnm: 0.2,
    },
  },
  {
    id: 'severe-coupling-cocking',
    name: 'Severe Angular Cocking & 2X Vibration',
    label: 'Severe Angular Cocking & 2X Vibration',
    simulator: 'alignment' as any,
    category: 'abnormal',
    event: 'Severe angular tilt between driver and driven hubs.',
    consequence: 'Extreme cyclic fatigue stress on disc pack, strong 2X harmonics.',
    recommendedAction: 'Install step shims under rear motor feet to correct tilt.',
    description: '1.45 mrad angular cocking induces high restoring moments on bearings.',
    events: [
      'Severe angular tilt between driver and driven hubs.',
      'Extreme cyclic fatigue stress on disc pack, strong 2X harmonics.',
    ],
    insight: 'Coupling flexible elements undergo alternating tension-compression cycles.',
    inputs: {
      motorRpm: 2950,
      couplingSpacerLengthMm: 140,
      couplingHubDiameterMm: 160,
      distCouplingToMotorFrontFootMm: 220,
      distMotorFrontToRearFootMm: 380,
      distCouplingToPumpFrontFootMm: 200,
      distPumpFrontToRearFootMm: 320,
      motorCenterlineHeightMm: 280,
      pumpCenterlineHeightMm: 280,
      ambientInstallationTempC: 20,
      motorOperatingTempC: 65,
      pumpFluidTempC: 85,
      pumpCasingMaterial: 'carbon_steel',
      thermalGrowthMode: 'auto_calculated',
      manualTargetVerticalOffsetMm: 0,
      manualTargetAngularOffsetMrad: 0,
      measurementMethod: 'dual_laser',
      measuredVerticalOffsetMm: -0.11,
      measuredVerticalAngleMrad: 1.45,
      measuredHorizontalOffsetMm: 0.02,
      measuredHorizontalAngleMrad: 0.65,
      indicatorBracketSagMm: 0.03,
      softFootFrontLeftMm: 0.02,
      softFootFrontRightMm: 0.03,
      softFootRearLeftMm: 0.02,
      softFootRearRightMm: 0.03,
      couplingType: 'metallic_disc_pack',
      angularStiffnessNmPerMrad: 450,
      radialStiffnessNPerMm: 1800,
      maxAllowableContinuousAngleDeg: 0.5,
      pipingInducedNozzleMomentKnm: 0.2,
    },
  },
  {
    id: 'soft-foot-violation',
    name: 'Soft Foot Baseplate Distortion',
    label: 'Soft Foot Baseplate Distortion',
    simulator: 'alignment' as any,
    category: 'abnormal',
    event: 'Rear-right anchor bolt released with 0.22 mm indicator deflection.',
    consequence: 'Motor frame twisted under torqued bolts, distorting bearing journals.',
    recommendedAction: 'Clean foot pads and install precision partial shims.',
    description: 'Uneven baseplate or twisted foot exceeding API 686 0.05 mm limit.',
    events: [
      'Rear-right anchor bolt released with 0.22 mm indicator deflection.',
      'Motor frame twisted under torqued bolts, distorting bearing journals.',
    ],
    insight: 'Soft foot induces 1X unbalance and electrical line-frequency motor vibration.',
    inputs: {
      motorRpm: 2950,
      couplingSpacerLengthMm: 140,
      couplingHubDiameterMm: 160,
      distCouplingToMotorFrontFootMm: 220,
      distMotorFrontToRearFootMm: 380,
      distCouplingToPumpFrontFootMm: 200,
      distPumpFrontToRearFootMm: 320,
      motorCenterlineHeightMm: 280,
      pumpCenterlineHeightMm: 280,
      ambientInstallationTempC: 20,
      motorOperatingTempC: 65,
      pumpFluidTempC: 85,
      pumpCasingMaterial: 'carbon_steel',
      thermalGrowthMode: 'auto_calculated',
      manualTargetVerticalOffsetMm: 0,
      manualTargetAngularOffsetMrad: 0,
      measurementMethod: 'dual_laser',
      measuredVerticalOffsetMm: -0.11,
      measuredVerticalAngleMrad: -0.15,
      measuredHorizontalOffsetMm: 0.02,
      measuredHorizontalAngleMrad: 0.04,
      indicatorBracketSagMm: 0.03,
      softFootFrontLeftMm: 0.02,
      softFootFrontRightMm: 0.04,
      softFootRearLeftMm: 0.03,
      softFootRearRightMm: 0.22,
      couplingType: 'metallic_disc_pack',
      angularStiffnessNmPerMrad: 450,
      radialStiffnessNPerMm: 1800,
      maxAllowableContinuousAngleDeg: 0.5,
      pipingInducedNozzleMomentKnm: 0.2,
    },
  },
];

export const ALL_SCENARIOS: Record<string, (ScenarioDefinition<any> & { name: string })[]> = {
  pump: PUMP_SCENARIOS,
  rotor: ROTOR_SCENARIOS,
  pipe: PIPE_SCENARIOS,
  seal: SEAL_SCENARIOS,
  alignment: ALIGNMENT_SCENARIOS,
};
