import { BearingFaultInputs } from '../types/bearing';
import { ScenarioItem } from '../components/Workbench/types';

export const BEARING_SCENARIOS: ScenarioItem<BearingFaultInputs>[] = [
  {
    id: 'nominal_clean',
    name: 'Nominal Sound Baseline (SKF 6309)',
    description: 'Fresh API 610 overhung pump radial bearing operating with full ISO VG 46 elastohydrodynamic film and zero raceway defects.',
    category: 'normal',
    inputs: {
      bearingId: 'skf_6309',
      shaftSpeedRpm: 2980,
      radialLoadKn: 4.5,
      axialLoadKn: 1.2,
      bearingTempC: 55,
      oilViscosityCSt: 46,
      faultLocation: 'none',
      faultSeverityPercent: 0,
      defectSizeMicrons: 20,
      sensorType: 'accelerometer',
      noiseLevelPercent: 5,
    },
  },
  {
    id: 'bpfo_stage2',
    name: 'Stage 2 Incipient Outer Race Flaking (BPFO)',
    description: 'Early localized spall on stationary outer raceway. Defect strikes rolling elements, generating prominent BPFO harmonics.',
    category: 'abnormal',
    inputs: {
      bearingId: 'skf_6309',
      shaftSpeedRpm: 2980,
      radialLoadKn: 5.8,
      axialLoadKn: 1.5,
      bearingTempC: 62,
      oilViscosityCSt: 46,
      faultLocation: 'outer_race',
      faultSeverityPercent: 28,
      defectSizeMicrons: 240,
      sensorType: 'accelerometer',
      noiseLevelPercent: 8,
    },
  },
  {
    id: 'bpfi_stage3',
    name: 'Stage 3 Advanced Inner Race Spall (BPFI + 1X Sidebands)',
    description: 'Severe spall on rotating inner ring passing through radial load zone once per rotation, creating distinct 1X amplitude-modulated sidebands.',
    category: 'abnormal',
    inputs: {
      bearingId: 'skf_6309',
      shaftSpeedRpm: 2980,
      radialLoadKn: 6.2,
      axialLoadKn: 2.0,
      bearingTempC: 78,
      oilViscosityCSt: 46,
      faultLocation: 'inner_race',
      faultSeverityPercent: 65,
      defectSizeMicrons: 850,
      sensorType: 'accelerometer',
      noiseLevelPercent: 12,
    },
  },
  {
    id: 'ball_spin_defect',
    name: 'Rolling Element Ball Spall & Cage Distress (2X BSF)',
    description: 'Chipped rolling element ball impacting both inner and outer raceways each spin period, generating 2X BSF with FTF cage sideband modulation.',
    category: 'abnormal',
    inputs: {
      bearingId: 'skf_6309',
      shaftSpeedRpm: 1485,
      radialLoadKn: 7.5,
      axialLoadKn: 1.8,
      bearingTempC: 72,
      oilViscosityCSt: 46,
      faultLocation: 'ball_spin',
      faultSeverityPercent: 52,
      defectSizeMicrons: 620,
      sensorType: 'accelerometer',
      noiseLevelPercent: 10,
    },
  },
  {
    id: 'stage4_terminal_breakdown',
    name: 'Stage 4 Terminal Breakdown & Loss of Clearance',
    description: 'Catastrophic flaking across multiple raceways and balls. Discrete harmonics washed out into broadband random friction grass.',
    category: 'abnormal',
    inputs: {
      bearingId: 'skf_6309',
      shaftSpeedRpm: 2980,
      radialLoadKn: 8.5,
      axialLoadKn: 3.5,
      bearingTempC: 98,
      oilViscosityCSt: 32,
      faultLocation: 'outer_race',
      faultSeverityPercent: 92,
      defectSizeMicrons: 2600,
      sensorType: 'accelerometer',
      noiseLevelPercent: 35,
    },
  },
  {
    id: 'lubrication_starvation',
    name: 'Lubricant Thermal Breakdown (Kappa κ < 0.4)',
    description: 'Elevated bearing housing temperature (92°C) causes extreme oil viscosity loss, breaking the elastohydrodynamic film into boundary metal contact.',
    category: 'abnormal',
    inputs: {
      bearingId: 'skf_6205',
      shaftSpeedRpm: 2980,
      radialLoadKn: 2.5,
      axialLoadKn: 0.5,
      bearingTempC: 92,
      oilViscosityCSt: 22,
      faultLocation: 'none',
      faultSeverityPercent: 0,
      defectSizeMicrons: 15,
      sensorType: 'high_freq_envelope',
      noiseLevelPercent: 15,
    },
  },
];
