import { CompressorInputs } from '../types/compressor';

export interface CompressorScenario {
  id: string;
  name: string;
  category: 'normal' | 'abnormal';
  event: string;
  consequence: string;
  recommendedAction: string;
  description: string;
  inputs: CompressorInputs;
}

export const COMPRESSOR_SCENARIOS: CompressorScenario[] = [
  {
    id: 'normal-steady-state',
    name: 'Normal Steady-State Baseline (Methane Gas)',
    category: 'normal',
    event: 'Steady process feed at 100% rated capacity.',
    consequence: 'Surge margin is a safe 25.5%, operating well right of the SCL.',
    recommendedAction: 'Keep anti-surge recycle valve closed on automatic standby.',
    description: 'Continuous process compression with stable head and nominal thrust loads.',
    inputs: {
      scenarioId: 'normal-steady-state',
      scenarioName: 'Normal Steady-State Baseline',
      gasType: 'natural_gas',
      suctionPressureBar: 18.0,
      suctionTempC: 35.0,
      massFlowKgS: 22.5,
      speedRpm: 10500,
      designSpeedRpm: 10500,
      asvOpeningPercent: 0,
      asvCv: 250,
      recycleCoolerTempC: 38.0,
      polytropicEfficiency: 0.82,
      impellerDiameterMm: 480,
      surgeMarginTargetPercent: 12.0,
    },
  },
  {
    id: 'process-turndown-surge-warning',
    name: 'Upstream Turndown (Entering SCL Warning Zone)',
    category: 'abnormal',
    event: 'Upstream separator unit tripped, reducing process feed to 19.2 kg/s.',
    consequence: 'Surge margin drops to 6.7%, breaching the API 670 12% control line buffer.',
    recommendedAction: 'Modulate Anti-Surge Valve open to at least 20% to prevent surge entry.',
    description: 'Process starvation causes operating point to drift toward the surge line.',
    inputs: {
      scenarioId: 'process-turndown-surge-warning',
      scenarioName: 'Upstream Turndown',
      gasType: 'natural_gas',
      suctionPressureBar: 18.0,
      suctionTempC: 35.0,
      massFlowKgS: 19.2,
      speedRpm: 10500,
      designSpeedRpm: 10500,
      asvOpeningPercent: 0,
      asvCv: 250,
      recycleCoolerTempC: 38.0,
      polytropicEfficiency: 0.81,
      impellerDiameterMm: 480,
      surgeMarginTargetPercent: 12.0,
    },
  },
  {
    id: 'catastrophic-deep-surge',
    name: 'Violent Deep Surge & Flow Reversal Event',
    category: 'abnormal',
    event: 'Discharge block valve throttled with ASV stuck closed (0%).',
    consequence: 'Flow drops to 13.5 kg/s (-25% left of SLL). Violent pressure pulsations and 185% thrust bearing overload.',
    recommendedAction: 'Emergency Fast Trip! Stroke ASV 100% open within < 1.5 seconds to equalize pressure.',
    description: 'Full aerodynamic breakdown with destructive cyclic flow oscillations and acoustic shock bangs.',
    inputs: {
      scenarioId: 'catastrophic-deep-surge',
      scenarioName: 'Violent Deep Surge Event',
      gasType: 'natural_gas',
      suctionPressureBar: 18.0,
      suctionTempC: 35.0,
      massFlowKgS: 13.5,
      speedRpm: 10500,
      designSpeedRpm: 10500,
      asvOpeningPercent: 0,
      asvCv: 250,
      recycleCoolerTempC: 38.0,
      polytropicEfficiency: 0.74,
      impellerDiameterMm: 480,
      surgeMarginTargetPercent: 12.0,
    },
  },
  {
    id: 'asv-recycle-recovery',
    name: 'Anti-Surge Recycle Loop Active (Auto Protection)',
    category: 'normal',
    event: 'Low process feed compensated by 45% Anti-Surge Valve opening.',
    consequence: 'Recycle loop injects 6.8 kg/s cool gas, restoring surge margin to 21.0%.',
    recommendedAction: 'Monitor recycle cooler outlet temperature to prevent thermal runaway.',
    description: 'Standard automatic protection loop restoring safe aerodynamic stability.',
    inputs: {
      scenarioId: 'asv-recycle-recovery',
      scenarioName: 'Anti-Surge Recycle Active',
      gasType: 'natural_gas',
      suctionPressureBar: 18.0,
      suctionTempC: 35.0,
      massFlowKgS: 15.0,
      speedRpm: 10500,
      designSpeedRpm: 10500,
      asvOpeningPercent: 45,
      asvCv: 250,
      recycleCoolerTempC: 38.0,
      polytropicEfficiency: 0.80,
      impellerDiameterMm: 480,
      surgeMarginTargetPercent: 12.0,
    },
  },
  {
    id: 'dense-gas-co2-compression',
    name: 'Dense Gas (CO2) Critical Point High-Pressure Service',
    category: 'normal',
    event: 'CO2 carbon capture stream with high molecular weight (44.01 g/mol).',
    consequence: 'Higher density and steep pressure gradient require strict surge control margin.',
    recommendedAction: 'Ensure polytropic efficiency and high gas power are tracked on motor load.',
    description: 'Heavy molecular weight gas producing high head and steep aerodynamic slope.',
    inputs: {
      scenarioId: 'dense-gas-co2-compression',
      scenarioName: 'Dense Gas (CO2) Service',
      gasType: 'co2',
      suctionPressureBar: 22.0,
      suctionTempC: 30.0,
      massFlowKgS: 24.0,
      speedRpm: 9200,
      designSpeedRpm: 10500,
      asvOpeningPercent: 10,
      asvCv: 250,
      recycleCoolerTempC: 32.0,
      polytropicEfficiency: 0.79,
      impellerDiameterMm: 480,
      surgeMarginTargetPercent: 15.0,
    },
  },
];
