import { GearboxInputs } from '../types/gearbox';

export interface GearboxScenario {
  id: string;
  name: string;
  description: string;
  category: string;
  inputs: GearboxInputs;
}

export const GEARBOX_SCENARIOS: GearboxScenario[] = [
  {
    id: 'api-613-turbomachinery-reducer',
    name: 'API 613 Turbomachinery High-Speed Compressor Speed Increaser',
    description: 'Motor-driven 4-pole electric motor (1490 RPM, 450 kW) stepping up to 7,450 RPM centrifugal compressor pinion via precision case-carburized double-helical gearing.',
    category: 'High-Speed Turbomachinery',
    inputs: {
      gearType: 'helical',
      ratedPowerKw: 450,
      inputSpeedRpm: 1490,
      pinionTeeth: 23,
      gearTeeth: 115,
      normalModuleMm: 4.5,
      faceWidthMm: 120,
      pressureAngleDeg: 20,
      helixAngleDeg: 15,
      backlashMm: 0.18,
      materialGrade: 'carburized_case_hardened',
      isoQualityGrade: 5,
      pinionHardnessHrc: 60,
      gearHardnessHrc: 58,
      lubricant: 'synthetic_pao_220',
      oilOperatingTempC: 55,
      surfaceRoughnessRaUm: 0.4,
      toothFault: 'none',
      pinionEccentricityUm: 8,
      applicationServiceFactor: 1.4,
    },
  },
  {
    id: 'cooling-tower-fan-drive',
    name: 'API 677 Cooling Tower Fan Right-Angle Helical Reducer',
    description: 'Electric motor (1780 RPM, 75 kW) driving large 8-blade cooling tower axial fan at 135 RPM in humid corrosive atmosphere.',
    category: 'Process Plant Infrastructure',
    inputs: {
      gearType: 'helical',
      ratedPowerKw: 75,
      inputSpeedRpm: 1780,
      pinionTeeth: 19,
      gearTeeth: 251,
      normalModuleMm: 5.0,
      faceWidthMm: 85,
      pressureAngleDeg: 20,
      helixAngleDeg: 12,
      backlashMm: 0.22,
      materialGrade: 'carburized_case_hardened',
      isoQualityGrade: 6,
      pinionHardnessHrc: 58,
      gearHardnessHrc: 56,
      lubricant: 'iso_vg_320',
      oilOperatingTempC: 62,
      surfaceRoughnessRaUm: 0.6,
      toothFault: 'none',
      pinionEccentricityUm: 14,
      applicationServiceFactor: 1.5,
    },
  },
  {
    id: 'pitch-line-pitting-fault',
    name: 'AGMA 2001 Contact Fatigue & Pitch-Line Macro Pitting',
    description: 'Overheated mineral oil and high Hertzian contact stress produce subsurface shear fatigue, crater pitting along the operating pitch line with emerging 1X gear-speed sidebands.',
    category: 'Fault Injection & Degradation',
    inputs: {
      gearType: 'spur',
      ratedPowerKw: 250,
      inputSpeedRpm: 1480,
      pinionTeeth: 21,
      gearTeeth: 89,
      normalModuleMm: 6.0,
      faceWidthMm: 95,
      pressureAngleDeg: 20,
      helixAngleDeg: 0,
      backlashMm: 0.20,
      materialGrade: 'through_hardened_steel',
      isoQualityGrade: 7,
      pinionHardnessHrc: 42,
      gearHardnessHrc: 38,
      lubricant: 'iso_vg_150',
      oilOperatingTempC: 85, // High temp thins oil
      surfaceRoughnessRaUm: 1.1,
      toothFault: 'pitch_line_pitting',
      pinionEccentricityUm: 35,
      applicationServiceFactor: 1.6,
    },
  },
  {
    id: 'broken-tooth-shock-impact',
    name: 'Broken Tooth Shock Impact with High GMF Sideband Forest',
    description: 'Severe shock overload or root fatigue propagation snapped 40% of a pinion tooth, generating massive 1X rotational impact transients and sidebands across the GMF harmonics.',
    category: 'Fault Injection & Degradation',
    inputs: {
      gearType: 'spur',
      ratedPowerKw: 310,
      inputSpeedRpm: 1480,
      pinionTeeth: 18,
      gearTeeth: 74,
      normalModuleMm: 6.5,
      faceWidthMm: 100,
      pressureAngleDeg: 20,
      helixAngleDeg: 0,
      backlashMm: 0.35,
      materialGrade: 'carburized_case_hardened',
      isoQualityGrade: 8,
      pinionHardnessHrc: 58,
      gearHardnessHrc: 56,
      lubricant: 'iso_vg_220',
      oilOperatingTempC: 68,
      surfaceRoughnessRaUm: 0.8,
      toothFault: 'broken_tooth',
      pinionEccentricityUm: 50,
      applicationServiceFactor: 1.8,
    },
  },
  {
    id: 'heavy-ball-mill-extruder',
    name: 'Heavy-Duty Extruder / Ball Mill Double-Reduction Helical',
    description: 'Extremely high torque transmission (1200 kW, 990 RPM to 125 RPM) with massive tangential loading and heavy shock service factor.',
    category: 'Heavy Mining & Polymers',
    inputs: {
      gearType: 'double_helical',
      ratedPowerKw: 1200,
      inputSpeedRpm: 990,
      pinionTeeth: 21,
      gearTeeth: 166,
      normalModuleMm: 9.0,
      faceWidthMm: 240,
      pressureAngleDeg: 20,
      helixAngleDeg: 22,
      backlashMm: 0.30,
      materialGrade: 'carburized_case_hardened',
      isoQualityGrade: 5,
      pinionHardnessHrc: 61,
      gearHardnessHrc: 59,
      lubricant: 'iso_vg_460',
      oilOperatingTempC: 60,
      surfaceRoughnessRaUm: 0.5,
      toothFault: 'none',
      pinionEccentricityUm: 12,
      applicationServiceFactor: 1.75,
    },
  },
];
