import { JournalBearingInputs } from '../types/journalBearing';
import { WorkbenchScenario } from '../components/Workbench/types';

export const JOURNAL_BEARING_SCENARIOS: WorkbenchScenario<JournalBearingInputs>[] = [
  {
    id: 'tpjb_steam_turbine_nominal',
    name: 'API 612 High-Speed Steam Turbine (5-Pad Tilting Pad)',
    description: 'High-speed 6,200 RPM turbine rotor equipped with 5-Pad Load-Between-Pad (LBP) tilting pad bearings. Hydrodynamic wedge is fully stable with zero cross-coupling.',
    category: 'normal',
    inputs: {
      bearingType: 'tilt_pad_5pad_lbp',
      journalDiameterMm: 120,
      bearingLengthMm: 90,
      radialClearanceUm: 90,
      shaftSpeedRpm: 6200,
      staticRadialLoadKn: 12.0,
      oilGrade: 'ISO_VG_46',
      oilSupplyTempC: 45,
      oilSupplyPressureBar: 1.8,
      rotorFirstCriticalSpeedRpm: 2800,
      unbalanceGmm: 45,
    },
  },
  {
    id: 'plain_sleeve_oil_whirl',
    name: 'Centrifugal Compressor Pinion (Subsynchronous Oil Whirl)',
    description: 'Lightly loaded 7,500 RPM pinion in a plain cylindrical sleeve. High Sommerfeld number drives large cross-coupled stiffness Kxy, generating self-excited oil whirl at 0.46X.',
    category: 'abnormal',
    inputs: {
      bearingType: 'plain_cylindrical',
      journalDiameterMm: 90,
      bearingLengthMm: 70,
      radialClearanceUm: 80,
      shaftSpeedRpm: 7500,
      staticRadialLoadKn: 3.5,
      oilGrade: 'ISO_VG_32',
      oilSupplyTempC: 42,
      oilSupplyPressureBar: 1.5,
      rotorFirstCriticalSpeedRpm: 3200,
      unbalanceGmm: 25,
    },
  },
  {
    id: 'oil_whip_catastrophic_resonance',
    name: 'Catastrophic Oil Whip Resonant Lock-in (Speed > 2X Critical)',
    description: 'Plain sleeve rotor accelerated to 6,800 RPM past twice its first lateral bending critical speed (2,600 RPM). Fluid whirl locks onto rotor natural frequency, triggering violent resonant oil whip.',
    category: 'abnormal',
    inputs: {
      bearingType: 'plain_cylindrical',
      journalDiameterMm: 100,
      bearingLengthMm: 80,
      radialClearanceUm: 85,
      shaftSpeedRpm: 6800,
      staticRadialLoadKn: 4.8,
      oilGrade: 'ISO_VG_46',
      oilSupplyTempC: 40,
      oilSupplyPressureBar: 1.5,
      rotorFirstCriticalSpeedRpm: 2600,
      unbalanceGmm: 30,
    },
  },
  {
    id: 'pressure_dam_stabilization',
    name: 'Engineering Fix: Pressure Dam Bearing Retrofit',
    description: 'The unstable compressor pinion retrofitted with a circumferential Pressure Dam. The hydrodynamic step generates downward preload, increasing eccentricity and suppressing whirl.',
    category: 'normal',
    inputs: {
      bearingType: 'pressure_dam',
      journalDiameterMm: 90,
      bearingLengthMm: 70,
      radialClearanceUm: 80,
      shaftSpeedRpm: 7500,
      staticRadialLoadKn: 3.5,
      oilGrade: 'ISO_VG_32',
      oilSupplyTempC: 42,
      oilSupplyPressureBar: 1.5,
      rotorFirstCriticalSpeedRpm: 3200,
      unbalanceGmm: 25,
    },
  },
  {
    id: 'cold_lube_oil_viscosity_surge',
    name: 'Cold Lube Oil Thermal Shock (Viscosity Spike During Startup)',
    description: 'Lube oil supply temperature at 24°C due to failed pre-heaters. High viscosity spikes Sommerfeld number into extreme unstable region during turbine run-up.',
    category: 'abnormal',
    inputs: {
      bearingType: 'plain_cylindrical',
      journalDiameterMm: 100,
      bearingLengthMm: 80,
      radialClearanceUm: 90,
      shaftSpeedRpm: 4500,
      staticRadialLoadKn: 6.0,
      oilGrade: 'ISO_VG_68',
      oilSupplyTempC: 24,
      oilSupplyPressureBar: 1.5,
      rotorFirstCriticalSpeedRpm: 2200,
      unbalanceGmm: 20,
    },
  },
  {
    id: 'heavy_load_babbitt_wipe_risk',
    name: 'Overloaded Low-Speed Journal (Boundary Rub & Wiping Danger)',
    description: 'High static rotor weight (38 kN) running at only 1,200 RPM. Hydrodynamic wedge collapses below 7 µm, causing metal-to-metal Babbitt wiping and high friction.',
    category: 'abnormal',
    inputs: {
      bearingType: 'plain_cylindrical',
      journalDiameterMm: 120,
      bearingLengthMm: 80,
      radialClearanceUm: 70,
      shaftSpeedRpm: 1200,
      staticRadialLoadKn: 38.0,
      oilGrade: 'ISO_VG_32',
      oilSupplyTempC: 65,
      oilSupplyPressureBar: 1.2,
      rotorFirstCriticalSpeedRpm: 2400,
      unbalanceGmm: 50,
    },
  },
];
