import { PipeInputs } from '../types/pipe';
import { ValidationPreset } from '../types/common';

export const PIPE_PRESETS: ValidationPreset<PipeInputs>[] = [
  {
    id: 'cold_installation',
    name: 'Cold Installation (Ambient State)',
    description: 'Piping system at ambient temperature (20°C) with no thermal growth and zero thermal stresses.',
    industry: 'Piping Erection & Pre-Commissioning',
    source: 'ASME B31.3 Ambient Reference',
    inputs: {
      scenarioId: 'cold_installation',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 15.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 20,
      operatingPressureBar: 0,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 100,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.5,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.0,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Expansion ΔL', expected: '0.0 mm', unit: 'mm' },
      { key: 'axialStressMPa', label: 'Axial Stress', expected: '0.0 MPa', unit: 'MPa' },
      { key: 'stressState', label: 'Status', expected: 'Safe', unit: '' },
    ],
  },
  {
    id: 'normal_heatup',
    name: 'Normal Heat-up (20°C → 85°C)',
    description: 'Moderate process fluid warm-up with controlled thermal growth across guided piping run.',
    industry: 'Process Utilities & Cooling Water',
    source: 'ASME B31.3 Normal Service',
    inputs: {
      scenarioId: 'normal_heatup',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 15.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 85,
      operatingPressureBar: 8.0,
      anchorCondition: 'guided',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 40,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.5,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.5,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Expansion ΔL', expected: '11.7 mm', unit: 'mm' },
      { key: 'stressRatioPercent', label: 'Stress Ratio', expected: '< 50%', unit: '%' },
      { key: 'stressState', label: 'Status', expected: 'Safe', unit: '' },
    ],
  },
  {
    id: 'hot_line_operation',
    name: 'Hot Line Operation (20°C → 180°C)',
    description: 'High-temperature process header operating under steady thermal and pressure loading.',
    industry: 'Refining & Petrochemical Units',
    source: 'ASME B31.3 Severe Cyclic Service',
    inputs: {
      scenarioId: 'hot_line_operation',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 20.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 180,
      operatingPressureBar: 20.0,
      anchorCondition: 'guided',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 60,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.5,
      expansionLoopHeightM: 4.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.0,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Growth ΔL', expected: '38.4 mm', unit: 'mm' },
      { key: 'stressState', label: 'Status', expected: 'Safe / Warning', unit: '' },
    ],
  },
  {
    id: 'fully_restrained_pipe',
    name: 'Fully Restrained Pipe (Fixed-Fixed)',
    description: 'Rigid straight line without expansion loops; 100% thermal restraint yields extreme axial compressive stress and anchor thrust.',
    industry: 'High-Pressure Steam Headers',
    source: 'ASME B31.3 Restrained Systems',
    inputs: {
      scenarioId: 'fully_restrained_pipe',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 20.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 160,
      operatingPressureBar: 15.0,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 100,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.0,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Theoretical Growth ΔL', expected: '33.6 mm', unit: 'mm' },
      { key: 'axialStressMPa', label: 'Restrained Axial Stress σ', expected: '336.0 MPa', unit: 'MPa' },
      { key: 'stressRatioPercent', label: 'Stress Capacity Ratio', expected: '> 200%', unit: '%' },
      { key: 'stressState', label: 'Status', expected: 'Critical', unit: '' },
    ],
  },
  {
    id: 'free_expansion',
    name: 'Free Expansion (Fixed-Free Cantilever)',
    description: 'One end anchored, opposite end resting on low-friction rollers; unrestricted expansion with zero thermal stress.',
    industry: 'Flare Headers & Overboard Blowdown',
    source: 'ASME B31.3 Appendix S',
    inputs: {
      scenarioId: 'free_expansion',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 25.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 170,
      operatingPressureBar: 5.0,
      anchorCondition: 'one_end_fixed_one_end_free',
      constraintFactorType: 'free_expansion',
      restraintPercent: 0,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 2,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.5,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Free Thermal Growth ΔL', expected: '45.0 mm', unit: 'mm' },
      { key: 'axialStressMPa', label: 'Axial Stress', expected: '0.0 MPa', unit: 'MPa' },
      { key: 'stressState', label: 'Status', expected: 'Safe', unit: '' },
    ],
  },
  {
    id: 'expansion_loop_active',
    name: 'Expansion Loop Active (Symmetrical U-Loop)',
    description: 'Engineered expansion U-loop safely absorbs 64.8 mm of thermal growth, keeping line stresses and nozzle thrust low.',
    industry: 'Refinery Interconnecting Pipe Racks',
    source: 'Kellogg Guided Cantilever Method',
    inputs: {
      scenarioId: 'expansion_loop_active',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 30.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 200,
      operatingPressureBar: 18.0,
      anchorCondition: 'expansion_loop',
      constraintFactorType: 'free_expansion',
      restraintPercent: 5,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 4.0,
      expansionLoopHeightM: 4.5,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.0,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Growth ΔL', expected: '64.8 mm', unit: 'mm' },
      { key: 'isExpansionLoopAdequate', label: 'Loop Adequacy', expected: 'Adequate', unit: '' },
      { key: 'stressRatioPercent', label: 'Stress Ratio', expected: '< 70%', unit: '%' },
      { key: 'stressState', label: 'Status', expected: 'Safe', unit: '' },
    ],
  },
  {
    id: 'failed_anchor',
    name: 'Failed Anchor (Structural Anchor Failure)',
    description: 'Terminal anchor foundation sheared or bolts parted; pipe loses axial constraint, shifting uncontrolled into adjacent equipment.',
    industry: 'Offshore & Heavy Industrial Plant Alarms',
    source: 'Plant Incident Investigation / Failure Mode',
    inputs: {
      scenarioId: 'failed_anchor',
      isAnchorFailed: true,
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 20.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 180,
      operatingPressureBar: 12.0,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 100,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.5,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'isAnchorFailed', label: 'Anchor Integrity', expected: 'Failed', unit: '' },
      { key: 'stressState', label: 'Status', expected: 'Critical Alarm', unit: '' },
    ],
  },
  {
    id: 'failed_support',
    name: 'Failed Support (Intermediate Guide Lost)',
    description: 'Intermediate guide shoe has slipped off structural steel beam, creating excessive unsupported span and gravitational bowing.',
    industry: 'Power Plant Pipe Rack Inspection',
    source: 'Piping Support Integrity Assessment',
    inputs: {
      scenarioId: 'failed_support',
      isSupportFailed: true,
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 24.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 150,
      operatingPressureBar: 10.0,
      anchorCondition: 'guided',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 50,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.5,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'isSupportFailed', label: 'Support Status', expected: 'Compromised', unit: '' },
      { key: 'stressState', label: 'Status', expected: 'Warning', unit: '' },
    ],
  },
  {
    id: 'thermal_shock',
    name: 'Thermal Shock (Rapid Hot Surge 20°C → 320°C)',
    description: 'Rapid hot fluid injection induces severe through-wall temperature gradient and high transient skin stresses.',
    industry: 'Boiler Blowdown & Steam Letdown',
    source: 'ASME Section VIII Div 2 Part 5',
    inputs: {
      scenarioId: 'thermal_shock',
      isThermalShock: true,
      materialType: 'alloy_steel',
      pipeSizePreset: 'DN200',
      pipeLengthM: 18.0,
      pipeOuterDiameterMm: 219.1,
      pipeWallThicknessMm: 12.7,
      installationTempC: 20,
      operatingTempC: 320,
      operatingPressureBar: 45.0,
      anchorCondition: 'guided',
      constraintFactorType: 'partially_restrained',
      restraintPercent: 75,
      modulusOfElasticityGPa: 205.0,
      thermalExpansionCoeff_1e6PerC: 13.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 4.5,
      expansionLoopHeightM: 4.5,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 1.5,
      nozzleLoadLimitKN: 25.0,
      npsNominalDiameterInches: 8,
      schedule: '80',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Expansion ΔL', expected: '70.2 mm', unit: 'mm' },
      { key: 'stressState', label: 'Status', expected: 'Critical / Warning', unit: '' },
    ],
  },
  {
    id: 'nozzle_overload_on_pump',
    name: 'Nozzle Overload on Pump (API 610 Overstress)',
    description: 'Excessive thermal thrust transferred directly to centrifugal pump suction/discharge flange, exceeding API 610 limits.',
    industry: 'Centrifugal Pump Station Reliability',
    source: 'API 610 Annex F / NEMA SM 23',
    inputs: {
      scenarioId: 'nozzle_overload_on_pump',
      isNozzleOverloadScenario: true,
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 18.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 175,
      operatingPressureBar: 16.0,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 90,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.5,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'isNozzleOverloaded', label: 'Pump Nozzle Load', expected: 'Overloaded (> API 610)', unit: '' },
      { key: 'stressState', label: 'Status', expected: 'Critical', unit: '' },
    ],
  },
  {
    id: 'benchmark_carbon_steel_10m',
    name: 'Validation Benchmark: Carbon Steel 10 m (20°C → 120°C)',
    description: '10 m Carbon Steel line with ΔT = 100°C. Exact benchmark: ΔL = 12.0 mm, Fully restrained σ = 240 MPa (Critical Overstress).',
    industry: 'Mechanical Engineering Validation Benchmark',
    source: 'ASME B31.3 / Physics Standard Test Case',
    inputs: {
      scenarioId: 'benchmark_carbon_steel_10m',
      materialType: 'carbon_steel',
      pipeSizePreset: 'DN150',
      pipeLengthM: 10.0,
      pipeOuterDiameterMm: 168.3,
      pipeWallThicknessMm: 7.11,
      installationTempC: 20,
      operatingTempC: 120,
      operatingPressureBar: 10.0,
      anchorCondition: 'anchored_both_ends',
      constraintFactorType: 'fully_restrained',
      restraintPercent: 100,
      modulusOfElasticityGPa: 200.0,
      thermalExpansionCoeff_1e6PerC: 12.0,
      allowableStressMPa: 137.9,
      expansionLoopWidthM: 3.0,
      expansionLoopHeightM: 3.0,
      numberOfBends: 4,
      jointFactor_Ej: 1.0,
      corrosionAllowanceMm: 0.0,
      nozzleLoadLimitKN: 18.0,
      npsNominalDiameterInches: 6,
      schedule: '40',
    },
    expectedOutputs: [
      { key: 'thermalExpansionMm', label: 'Thermal Expansion ΔL', expected: '12.0 mm', unit: 'mm' },
      { key: 'axialStressMPa', label: 'Fully Restrained Axial Stress σ', expected: '240.0 MPa', unit: 'MPa' },
      { key: 'stressRatioPercent', label: 'Stress Capacity Ratio', expected: '> 170%', unit: '%' },
      { key: 'stressState', label: 'ASME Status', expected: 'Critical Overstress', unit: '' },
    ],
  },
];
