import { PumpInputs } from '../types/pump';
import { ValidationPreset } from '../types/common';

export const PUMP_PRESETS: ValidationPreset<PumpInputs>[] = [
  {
    id: 'normal_operation',
    name: 'Normal Operation (Flooded Suction)',
    description: 'Clean water at 20°C pumped from an elevated open storage tank (+3.5m static head) with wide-open valves and low friction.',
    industry: 'Municipal & Industrial Water',
    source: 'Hydraulic Institute 9.6.1 Standard',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'flooded_suction',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 3.5,
      pipeLengthM: 8,
      pipeDiameterMm: 150,
      pipeRoughnessMm: 0.045,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 150,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 1,
        teeBranchFlow: 0,
        entranceLoss: 'radiused',
      },
      flowRateM3h: 120,
      bepFlowM3h: 130,
      ratedHeadM: 60,
      shutOffHeadM: 72,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 130,
      npshrInputMode: 'single_value',
      npshr3percentM: 2.8,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'npshaM', label: 'NPSHa', expected: '> 13 m', unit: 'm' },
      { key: 'npshMarginRatio', label: 'Margin Ratio', expected: '> 4.5x', unit: 'ratio' },
      { key: 'status', label: 'Status', expected: 'Safe (Optimal)', unit: '' },
    ],
  },
  {
    id: 'validation_benchmark_open_tank',
    name: 'Validation Benchmark: Water 20°C (2m Lift, 0.5m Loss)',
    description: 'Reference engineering test case: Water at 20°C, open tank with 2.0m suction lift and 0.5m pipe friction. Validates NPSHa ≈ 7.6m & NPSH Margin ≈ 4.6m (NPSHr = 3m).',
    industry: 'Hydraulic Benchmark Standard',
    source: 'Hydraulic Institute Standard Benchmark',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'open_tank',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: -2.0, // 2m suction lift
      pipeLengthM: 10,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.045,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 1,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
      flowRateM3h: 80,
      bepFlowM3h: 80,
      ratedHeadM: 45,
      shutOffHeadM: 55,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 110,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.0,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'atmosphericHeadM', label: 'Atmospheric Head', expected: '≈ 10.33 m', unit: 'm' },
      { key: 'staticSuctionHeadM', label: 'Static Lift', expected: '-2.0 m', unit: 'm' },
      { key: 'totalSuctionHeadLossM', label: 'Suction Loss', expected: '≈ 0.50 m', unit: 'm' },
      { key: 'vaporPressureHeadM', label: 'Vapor Head', expected: '≈ 0.24 m', unit: 'm' },
      { key: 'npshaM', label: 'NPSHa', expected: '≈ 7.6 m', unit: 'm' },
      { key: 'npshMarginM', label: 'NPSH Margin', expected: '≈ 4.6 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Safe', unit: '' },
    ],
  },
  {
    id: 'low_suction_level',
    name: 'Low Suction Level (Critical Lift)',
    description: 'Suction pit liquid level dropped to -4.2m below pump centerline. NPSHa drops below NPSHr triggering cavitation.',
    industry: 'Water Treatment & Sumps',
    source: 'ISO 5199 Chemical Pump Guidelines',
    inputs: {
      fluidId: 'water',
      fluidTempC: 22,
      suctionSourceType: 'suction_lift',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: -4.2,
      pipeLengthM: 14,
      pipeDiameterMm: 100,
      pipeRoughnessMm: 0.05,
      foulingFactor: 1.1,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 100,
      fittings: {
        standard90Elbow: 3,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 1,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'reentrant',
      },
      flowRateM3h: 90,
      bepFlowM3h: 90,
      ratedHeadM: 50,
      shutOffHeadM: 60,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 105,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.5,
      safetyMarginType: 'normal',
      pumpType: 'ansi_chemical',
      serviceStandard: 'iso5199',
    },
    expectedOutputs: [
      { key: 'staticSuctionHeadM', label: 'Static Lift', expected: '-4.2 m', unit: 'm' },
      { key: 'npshaM', label: 'NPSHa', expected: '< 3.5 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Critical Cavitation', unit: '' },
    ],
  },
  {
    id: 'hot_condensate',
    name: 'Hot Condensate (High Vapor Pressure)',
    description: 'High-temperature condensate / boiler feedwater at 95°C near boiling point. High vapor pressure head erodes NPSH margin.',
    industry: 'Thermal Power & Steam Utilities',
    source: 'API 610 / HI Steam Plant Practice',
    inputs: {
      fluidId: 'boiler_feed',
      fluidTempC: 95,
      suctionSourceType: 'pressurized_vessel',
      tankPressureKPag: 12,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 2.0,
      pipeLengthM: 16,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.06,
      foulingFactor: 1.15,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'low_npshr',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 4,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 1,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 1,
        entranceLoss: 'sharp',
      },
      flowRateM3h: 110,
      bepFlowM3h: 120,
      ratedHeadM: 120,
      shutOffHeadM: 145,
      pumpSpeedRpm: 2950,
      impellerEyeDiameterMm: 120,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.2,
      safetyMarginType: 'conservative',
      pumpType: 'between_bearing_bb2',
      serviceStandard: 'api610',
    },
    expectedOutputs: [
      { key: 'vaporPressureHeadM', label: 'Vapor Head', expected: '≈ 8.8 m', unit: 'm' },
      { key: 'npshaM', label: 'NPSHa', expected: '< 3.5 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Critical / Warning', unit: '' },
    ],
  },
  {
    id: 'suction_strainer_blocked',
    name: 'Suction Strainer Blocked (Fouled Mesh)',
    description: 'Suction basket strainer severely fouled with debris (Fouling Factor = 2.0). Causes massive localized pressure drop.',
    industry: 'Refining & Petrochemical',
    source: 'Field Troubleshooting Case Study',
    inputs: {
      fluidId: 'water',
      fluidTempC: 25,
      suctionSourceType: 'flooded_suction',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 1.5,
      pipeLengthM: 10,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.05,
      foulingFactor: 2.2, // Severely fouled strainer
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
      flowRateM3h: 100,
      bepFlowM3h: 100,
      ratedHeadM: 55,
      shutOffHeadM: 68,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 2.9,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'totalSuctionHeadLossM', label: 'Suction Loss', expected: '> 2.0 m', unit: 'm' },
      { key: 'npshaM', label: 'NPSHa', expected: 'Sub-critical', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Warning / Blocked', unit: '' },
    ],
  },
  {
    id: 'suction_valve_throttled',
    name: 'Suction Valve Throttled (Operator Error)',
    description: 'Suction isolation valve erroneously throttled to 25% opening. Causes severe cavitation and acoustic noise at impeller.',
    industry: 'Plant Operations / Human Factors',
    source: 'Hydraulic Institute Bad Practice Case',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'flooded_suction',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 2.0,
      pipeLengthM: 10,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.045,
      foulingFactor: 1.0,
      valveOpeningPercent: 25, // 25% throttled
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'radiused',
      },
      flowRateM3h: 90,
      bepFlowM3h: 100,
      ratedHeadM: 50,
      shutOffHeadM: 62,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 115,
      npshrInputMode: 'single_value',
      npshr3percentM: 2.8,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'totalSuctionHeadLossM', label: 'Valve Head Loss', expected: '> 3.5 m', unit: 'm' },
      { key: 'npshaM', label: 'NPSHa', expected: '< 2.5 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Critical Cavitation', unit: '' },
    ],
  },
  {
    id: 'high_flow_demand',
    name: 'High Flow Demand (Runout Flow Condition)',
    description: 'Pump operated at 135% of BEP flow. NPSHr escalates sharply along power-law curve while line friction quadruples.',
    industry: 'Cooling Water Circulation',
    source: 'Hydraulic Institute High Flow Instability',
    inputs: {
      fluidId: 'water',
      fluidTempC: 30,
      suctionSourceType: 'flooded_suction',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 1.5,
      pipeLengthM: 15,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.05,
      foulingFactor: 1.15,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'high_flow',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 3,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 1,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
      flowRateM3h: 165,
      bepFlowM3h: 120,
      ratedHeadM: 65,
      shutOffHeadM: 80,
      pumpSpeedRpm: 2950,
      impellerEyeDiameterMm: 130,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.6,
      safetyMarginType: 'conservative',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'operatingPercentBEP', label: 'Flow % BEP', expected: '> 135% (Runout)', unit: '%' },
      { key: 'npshrM', label: 'NPSHr at Duty Flow', expected: '> 5.5 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Critical / Cavitation Likely', unit: '' },
    ],
  },
  {
    id: 'gas_entrainment',
    name: 'Gas Entrainment (Free Air Ingestion)',
    description: 'Vortex formation or leaking suction packing pulls 6% free air/gas into the suction line, causing air pocket locking and head degradation.',
    industry: 'Mineral Processing & Chemical',
    source: 'Hydraulic Institute Slurry & Aerated Fluid Guide',
    inputs: {
      fluidId: 'water',
      fluidTempC: 22,
      suctionSourceType: 'open_tank',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 0.8,
      pipeLengthM: 10,
      pipeDiameterMm: 125,
      pipeRoughnessMm: 0.045,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 6, // 6% air pockets
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 125,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 0,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'sharp',
      },
      flowRateM3h: 75,
      bepFlowM3h: 90,
      ratedHeadM: 48,
      shutOffHeadM: 58,
      pumpSpeedRpm: 1450,
      impellerEyeDiameterMm: 110,
      npshrInputMode: 'single_value',
      npshr3percentM: 3.0,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'npshaM', label: 'NPSHa', expected: '~ 7.5 m', unit: 'm' },
      { key: 'status', label: 'Status', expected: 'Warning (Air Locking)', unit: '' },
    ],
  },
  {
    id: 'rapid_pump_trip',
    name: 'Rapid Pump Trip (Transient Inertial Decel)',
    description: 'Sudden electrical trip while running. Flow rate drops rapidly and suction line experiences dynamic deceleration pulses.',
    industry: 'Power Generation & Pipeline Safety',
    source: 'Water Hammer & Transient Analysis Case',
    inputs: {
      fluidId: 'water',
      fluidTempC: 20,
      suctionSourceType: 'flooded_suction',
      tankPressureKPag: 0,
      atmosphericPressureKPa: 101.325,
      staticHeadM: 2.5,
      pipeLengthM: 10,
      pipeDiameterMm: 150,
      pipeRoughnessMm: 0.045,
      foulingFactor: 1.0,
      valveOpeningPercent: 100,
      gasEntrainmentPercent: 0,
      pumpPresetModel: 'standard',
      pipeDiameterChangeMm: 150,
      fittings: {
        standard90Elbow: 2,
        longRadius90Elbow: 0,
        gateValveOpen: 1,
        butterflyValve: 0,
        swingCheckValve: 1,
        suctionStrainer: 1,
        teeFlowThrough: 0,
        teeBranchFlow: 0,
        entranceLoss: 'radiused',
      },
      flowRateM3h: 20,
      bepFlowM3h: 130,
      ratedHeadM: 60,
      shutOffHeadM: 72,
      pumpSpeedRpm: 400,
      impellerEyeDiameterMm: 130,
      npshrInputMode: 'single_value',
      npshr3percentM: 1.5,
      safetyMarginType: 'normal',
      pumpType: 'overhung_oh2',
      serviceStandard: 'hydraulic_institute',
    },
    expectedOutputs: [
      { key: 'operatingPercentBEP', label: 'Flow % BEP', expected: '< 20% (Tripped)', unit: '%' },
      { key: 'status', label: 'Status', expected: 'Tripped', unit: '' },
    ],
  },
];
