import { RecipCompressorInputs } from '../types/recipCompressor';
import { WorkbenchScenario } from '../components/Workbench/types';

export const RECIP_COMPRESSOR_SCENARIOS: WorkbenchScenario<RecipCompressorInputs>[] = [
  {
    id: 'recip-nominal',
    name: 'Nominal API 618 Natural Gas Booster (Double Acting)',
    description: 'Balanced double-acting cylinder with tuned API 688 acoustic pulsation bottles, healthy valves, and full rod load reversal.',
    inputs: {
      cylinderBoreMm: 280,
      strokeMm: 200,
      connectingRodLengthMm: 600,
      pistonRodDiameterMm: 65,
      crankSpeedRpm: 600,
      cylinderAction: 'double_acting',
      heClearancePercent: 12,
      ceClearancePercent: 14,
      reciprocatingMassKg: 160,
      rodLoadTensionLimitKn: 140,
      rodLoadCompressionLimitKn: 150,
      gasType: 'natural_gas_methane',
      suctionPressureBarA: 4.5,
      suctionTempC: 35,
      dischargePressureBarA: 18.0,
      suctionValveFault: 'normal',
      dischargeValveFault: 'normal',
      pistonRingCondition: 'good',
      hasPulsationBottles: true,
      damperVolumeLiters: 450,
      chokeTubeDiameterMm: 100,
      chokeTubeLengthMm: 600,
      pipingLengthToFirstElbowM: 4.2,
    },
  },
  {
    id: 'recip-suction-valve-leak',
    name: 'Suction Valve Leak (Degraded Compression & Churn Heat)',
    description: 'Leaking suction valve allows compressed gas to back-flow into suction manifold, flattening compression slope and increasing discharge temperature.',
    inputs: {
      cylinderBoreMm: 280,
      strokeMm: 200,
      connectingRodLengthMm: 600,
      pistonRodDiameterMm: 65,
      crankSpeedRpm: 600,
      cylinderAction: 'double_acting',
      heClearancePercent: 12,
      ceClearancePercent: 14,
      reciprocatingMassKg: 160,
      rodLoadTensionLimitKn: 140,
      rodLoadCompressionLimitKn: 150,
      gasType: 'natural_gas_methane',
      suctionPressureBarA: 4.5,
      suctionTempC: 35,
      dischargePressureBarA: 18.0,
      suctionValveFault: 'severe_leak',
      dischargeValveFault: 'normal',
      pistonRingCondition: 'good',
      hasPulsationBottles: true,
      damperVolumeLiters: 450,
      chokeTubeDiameterMm: 100,
      chokeTubeLengthMm: 600,
      pipingLengthToFirstElbowM: 4.2,
    },
  },
  {
    id: 'recip-discharge-valve-leak',
    name: 'Discharge Valve Failure (Re-expansion PV Collapse)',
    description: 'Severe discharge valve leakage forces high-pressure gas back into cylinder during intake stroke, causing late suction opening and volumetric efficiency collapse.',
    inputs: {
      cylinderBoreMm: 280,
      strokeMm: 200,
      connectingRodLengthMm: 600,
      pistonRodDiameterMm: 65,
      crankSpeedRpm: 600,
      cylinderAction: 'double_acting',
      heClearancePercent: 12,
      ceClearancePercent: 14,
      reciprocatingMassKg: 160,
      rodLoadTensionLimitKn: 140,
      rodLoadCompressionLimitKn: 150,
      gasType: 'natural_gas_methane',
      suctionPressureBarA: 4.5,
      suctionTempC: 35,
      dischargePressureBarA: 18.0,
      suctionValveFault: 'normal',
      dischargeValveFault: 'severe_leak',
      pistonRingCondition: 'good',
      hasPulsationBottles: true,
      damperVolumeLiters: 450,
      chokeTubeDiameterMm: 100,
      chokeTubeLengthMm: 600,
      pipingLengthToFirstElbowM: 4.2,
    },
  },
  {
    id: 'recip-no-load-reversal',
    name: 'API 618 No Rod Load Reversal Hazard (Wrist Pin Starvation)',
    description: 'Imbalanced pressure regime producing zero load reversal (< 5° crank rotation). Lubricating oil cannot replenish crosshead pin bushing, threatening immediate mechanical seizure.',
    inputs: {
      cylinderBoreMm: 340,
      strokeMm: 220,
      connectingRodLengthMm: 650,
      pistonRodDiameterMm: 70,
      crankSpeedRpm: 450,
      cylinderAction: 'single_acting_he',
      heClearancePercent: 10,
      ceClearancePercent: 12,
      reciprocatingMassKg: 110,
      rodLoadTensionLimitKn: 150,
      rodLoadCompressionLimitKn: 160,
      gasType: 'natural_gas_methane',
      suctionPressureBarA: 12.0,
      suctionTempC: 30,
      dischargePressureBarA: 28.0,
      suctionValveFault: 'normal',
      dischargeValveFault: 'normal',
      pistonRingCondition: 'good',
      hasPulsationBottles: true,
      damperVolumeLiters: 500,
      chokeTubeDiameterMm: 100,
      chokeTubeLengthMm: 600,
      pipingLengthToFirstElbowM: 4.0,
    },
  },
  {
    id: 'recip-acoustic-pulsation',
    name: 'API 688 Piping Acoustic Standing Wave Resonance',
    description: 'Surge dampener bottles bypassed/missing with pipe standing wave matching 2X cylinder pulsation harmonic, exceeding API 618 allowable acoustic pressure limit.',
    inputs: {
      cylinderBoreMm: 280,
      strokeMm: 200,
      connectingRodLengthMm: 600,
      pistonRodDiameterMm: 65,
      crankSpeedRpm: 600,
      cylinderAction: 'double_acting',
      heClearancePercent: 12,
      ceClearancePercent: 14,
      reciprocatingMassKg: 160,
      rodLoadTensionLimitKn: 140,
      rodLoadCompressionLimitKn: 150,
      gasType: 'natural_gas_methane',
      suctionPressureBarA: 4.5,
      suctionTempC: 35,
      dischargePressureBarA: 18.0,
      suctionValveFault: 'normal',
      dischargeValveFault: 'normal',
      pistonRingCondition: 'good',
      hasPulsationBottles: false,
      damperVolumeLiters: 450,
      chokeTubeDiameterMm: 100,
      chokeTubeLengthMm: 600,
      pipingLengthToFirstElbowM: 4.8,
    },
  },
  {
    id: 'recip-hydrogen-refinery',
    name: 'Refinery Hydrogen (H₂) High-Speed Hydrotreater Compressor',
    description: 'High-purity light molecular weight H₂ service with extremely high speed of sound (~1300 m/s), high rod loads, and tight API 618 tolerances.',
    inputs: {
      cylinderBoreMm: 240,
      strokeMm: 180,
      connectingRodLengthMm: 550,
      pistonRodDiameterMm: 60,
      crankSpeedRpm: 720,
      cylinderAction: 'double_acting',
      heClearancePercent: 14,
      ceClearancePercent: 16,
      reciprocatingMassKg: 130,
      rodLoadTensionLimitKn: 120,
      rodLoadCompressionLimitKn: 130,
      gasType: 'hydrogen_h2',
      suctionPressureBarA: 20.0,
      suctionTempC: 40,
      dischargePressureBarA: 65.0,
      suctionValveFault: 'normal',
      dischargeValveFault: 'normal',
      pistonRingCondition: 'good',
      hasPulsationBottles: true,
      damperVolumeLiters: 350,
      chokeTubeDiameterMm: 80,
      chokeTubeLengthMm: 500,
      pipingLengthToFirstElbowM: 3.5,
    },
  },
];
