import { RotorInputs } from '../types/rotor';
import { ValidationPreset } from '../types/common';

export const ROTOR_PRESETS: ValidationPreset<RotorInputs>[] = [
  {
    id: 'balanced_rotor',
    name: 'Balanced Rotor (ISO Grade G2.5 Precision)',
    description: 'Precision balanced rotor operating within ISO 1940 Grade G2.5 allowable unbalance limits with healthy bearing fatigue life.',
    industry: 'Turbomachinery & Industrial Drives',
    source: 'ISO 1940-1 & ISO 10816-3',
    inputs: {
      scenarioId: 'balanced_rotor',
      scenarioName: 'Balanced Rotor',
      rotorMassKg: 80,
      operatingRpm: 1800,
      unbalanceMassGrams: 0.8,
      unbalanceRadiusMm: 120, // U = 96 g·mm (U_per ≈ 1061 g·mm)
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 6.5, // C/P = 10.0 -> L10 = 1000M revs, ~9259 hrs
      staticRadialLoadN: 700,
      axialLoadN: 150,
      lubricationCondition: 'good',
      contaminationLevel: 'clean',
      reliabilityTarget: 0.90,
      machineType: 'motor',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 60,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 650,
      overhungLengthMm: 0,
      loadDistributionFactor: 0.50,
    },
    expectedOutputs: [
      { key: 'unbalanceRatio', label: 'Unbalance Ratio', expected: '< 0.15x', unit: 'x' },
      { key: 'iso10816Zone', label: 'Vibration Zone', expected: 'Zone A (< 1.12 mm/s)', unit: '' },
      { key: 'bearingLifeStatus', label: 'Bearing Life', expected: 'Safe (> 10,000 hrs)', unit: '' },
    ],
  },
  {
    id: 'mild_unbalance',
    name: 'Mild Unbalance (Elevated 1X Vibration)',
    description: 'Rotor with mild residual unbalance causing noticeable 1X synchronous vibration velocity in ISO 10816 Zone B.',
    industry: 'Industrial Fans & Blowers',
    source: 'ISO 10816-3 Zone B Standard',
    inputs: {
      scenarioId: 'mild_unbalance',
      scenarioName: 'Mild Unbalance',
      rotorMassKg: 100,
      operatingRpm: 2400,
      unbalanceMassGrams: 5.0,
      unbalanceRadiusMm: 150, // U = 750 g·mm
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 8.0,
      staticRadialLoadN: 900,
      axialLoadN: 200,
      lubricationCondition: 'normal',
      contaminationLevel: 'clean',
      reliabilityTarget: 0.90,
      machineType: 'fan',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 55,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 700,
      overhungLengthMm: 0,
      loadDistributionFactor: 0.50,
    },
    expectedOutputs: [
      { key: 'dynamicUnbalanceForceN', label: 'Centrifugal Force', expected: '~ 474 N', unit: 'N' },
      { key: 'iso10816Zone', label: 'Vibration Zone', expected: 'Zone B', unit: '' },
    ],
  },
  {
    id: 'heavy_unbalance',
    name: 'Heavy Unbalance (Severe 1X Force & Alarm)',
    description: 'Substantial mass unbalance exceeding ISO 1940 Grade limit, generating high centrifugal unbalance force into the bearing housings.',
    industry: 'Heavy Industrial Equipment',
    source: 'ISO 10816-3 Zone C/D Thresholds',
    inputs: {
      scenarioId: 'heavy_unbalance',
      scenarioName: 'Heavy Unbalance',
      rotorMassKg: 120,
      operatingRpm: 2950,
      unbalanceMassGrams: 22.0,
      unbalanceRadiusMm: 180, // U = 3960 g·mm
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '7312_becbm',
      basicDynamicLoadC_kN: 104,
      useDirectLoadP: false,
      equivalentLoadP_kN: 14.0,
      staticRadialLoadN: 1200,
      axialLoadN: 300,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 70,
      dampingRatio: 0.04,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 800,
      overhungLengthMm: 100,
      loadDistributionFactor: 0.60,
    },
    expectedOutputs: [
      { key: 'dynamicUnbalanceForceN', label: 'Centrifugal Force', expected: '> 3,700 N', unit: 'N' },
      { key: 'iso10816Zone', label: 'Vibration Zone', expected: 'Zone C / D (Alert)', unit: '' },
      { key: 'unbalanceRatio', label: 'Unbalance Ratio', expected: '> 3.5x Limit', unit: 'x' },
    ],
  },
  {
    id: 'blade_loss_event',
    name: 'Blade Loss Event (Sudden High Impact Unbalance)',
    description: 'Catastrophic simulated blade detachment event creating massive sudden eccentricity, high shaft whirl, and housing vibration shock.',
    industry: 'Turbomachinery / Gas & Steam Turbines',
    source: 'API 684 Blade Shedding Dynamics',
    inputs: {
      scenarioId: 'blade_loss_event',
      scenarioName: 'Blade Loss Event',
      rotorMassKg: 150,
      operatingRpm: 3600,
      unbalanceMassGrams: 45.0,
      unbalanceRadiusMm: 240, // U = 10,800 g·mm
      balanceGrade: 'G2.5',
      bearingType: 'roller',
      bearingCategorySelect: 'roller',
      bearingModelId: 'nu_310_ecp',
      basicDynamicLoadC_kN: 114,
      useDirectLoadP: false,
      equivalentLoadP_kN: 22.0,
      staticRadialLoadN: 1500,
      axialLoadN: 400,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'compressor',
      machineClass: 'class_3_large_rigid',
      rotorStiffnessKNmm: 65,
      dampingRatio: 0.035,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 900,
      overhungLengthMm: 150,
      loadDistributionFactor: 0.70,
    },
    expectedOutputs: [
      { key: 'dynamicUnbalanceForceN', label: 'Centrifugal Force', expected: '> 15,000 N', unit: 'N' },
      { key: 'iso10816Zone', label: 'Vibration Severity', expected: 'Zone D (Emergency Trip)', unit: '' },
      { key: 'vibrationDisplacementPkPkMicrons', label: 'Peak Orbit Displacement', expected: '> 100 µm pk-pk', unit: 'µm' },
    ],
  },
  {
    id: 'near_critical_speed',
    name: 'Near Critical Speed (Resonance Amplification)',
    description: 'Rotor operating at λ ≈ 1.00 directly on the 1st lateral critical speed with dynamic magnification causing excessive shaft deflection.',
    industry: 'Turbomachinery / Resonance Dynamics',
    source: 'API 684 Rotor Dynamics & SDOF Resonance',
    inputs: {
      scenarioId: 'near_critical_speed',
      scenarioName: 'Near Critical Speed',
      rotorMassKg: 160,
      operatingRpm: 3000,
      unbalanceMassGrams: 12.0,
      unbalanceRadiusMm: 180, // U = 2160 g·mm
      balanceGrade: 'G2.5',
      bearingType: 'roller',
      bearingCategorySelect: 'roller',
      bearingModelId: 'nu_310_ecp',
      basicDynamicLoadC_kN: 114,
      useDirectLoadP: false,
      equivalentLoadP_kN: 15.0,
      staticRadialLoadN: 1600,
      axialLoadN: 0,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'compressor',
      machineClass: 'class_3_large_rigid',
      rotorStiffnessKNmm: 15.8, // Critical speed ≈ 3000 RPM (λ ≈ 1.00)
      dampingRatio: 0.03, // Low damping -> huge Q factor
      bearingPosition: 'overhung',
      bearingSpanMm: 750,
      overhungLengthMm: 280,
      loadDistributionFactor: 0.75,
    },
    expectedOutputs: [
      { key: 'speedRatioLambda', label: 'Speed Ratio (λ)', expected: '0.98 - 1.02 (Resonance)', unit: '' },
      { key: 'isNearCriticalSpeed', label: 'Resonance Zone Active', expected: 'true', unit: '' },
      { key: 'iso10816Zone', label: 'Vibration Zone', expected: 'Zone D', unit: '' },
    ],
  },
  {
    id: 'lubrication_loss',
    name: 'Lubrication Loss (Thermal Degradation & Life Drop)',
    description: 'Loss of elastohydrodynamic lubricant film (κ < 0.4) causing severe bearing frictional heat and rapid fatigue life drop by 50-80%.',
    industry: 'Industrial Process Pumps & Fans',
    source: 'ISO 281 Lubrication Factor a_lube Degradation',
    inputs: {
      scenarioId: 'lubrication_loss',
      scenarioName: 'Lubrication Loss',
      rotorMassKg: 90,
      operatingRpm: 1800,
      unbalanceMassGrams: 1.5,
      unbalanceRadiusMm: 120,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 8.125, // Basic L10h = 4,741 hrs
      staticRadialLoadN: 800,
      axialLoadN: 150,
      lubricationCondition: 'poor', // a_lube = 0.50
      contaminationLevel: 'contaminated', // a_contam = 0.40
      reliabilityTarget: 0.95, // a1 = 0.64 -> a_mod = 0.128x -> L10mh ≈ 607 hrs
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 50,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 650,
      overhungLengthMm: 0,
      loadDistributionFactor: 0.50,
      bearingOperatingTempC: 95,
    },
    expectedOutputs: [
      { key: 'combinedLifeFactorAmod', label: 'Life Modifier a_mod', expected: '0.128x (Severe)', unit: 'x' },
      { key: 'modifiedLifeL10mhHours', label: 'Modified Life L10mh', expected: '~ 607 hrs', unit: 'hrs' },
      { key: 'bearingLifeStatus', label: 'Bearing Life Status', expected: 'Critical (< 8,000 hrs)', unit: '' },
    ],
  },
  {
    id: 'bearing_overload',
    name: 'Bearing Overload (High Equivalent Load P, Low C/P)',
    description: 'High static/dynamic radial load driving C/P < 4.0, causing accelerated subsurface fatigue and reduced rolling element life.',
    industry: 'Heavy Slurry Pumps & Crushers',
    source: 'ISO 281 Rating Life C/P Ratio Standard',
    inputs: {
      scenarioId: 'bearing_overload',
      scenarioName: 'Bearing Overload',
      rotorMassKg: 180,
      operatingRpm: 1500,
      unbalanceMassGrams: 8.0,
      unbalanceRadiusMm: 150,
      balanceGrade: 'G6.3',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65,
      useDirectLoadP: true,
      equivalentLoadP_kN: 22.0, // C/P = 65/22 = 2.95 -> L10 = (2.95)^3 = 25.8M revs, L10h = 286 hrs!
      staticRadialLoadN: 3500,
      axialLoadN: 1200,
      lubricationCondition: 'normal',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.90,
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 45,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 700,
      overhungLengthMm: 120,
      loadDistributionFactor: 0.70,
    },
    expectedOutputs: [
      { key: 'loadRatioCP', label: 'C/P Load Ratio', expected: '< 3.2x (Severe Overload)', unit: 'x' },
      { key: 'basicLifeL10hHours', label: 'Basic Life L10h', expected: '< 500 hrs', unit: 'hrs' },
      { key: 'bearingLifeStatus', label: 'Bearing Life Status', expected: 'Critical Alert', unit: '' },
    ],
  },
  {
    id: 'high_temp_degradation',
    name: 'High Temperature Bearing Degradation (Thermal Expansion)',
    description: 'High operating temperature (105°C) inducing lubricant viscosity breakdown, thermal cage degradation, and micro-spalling risk.',
    industry: 'Hot Gas Blowers & Boiler Feed Pumps',
    source: 'ISO 281 & DIN 51517 Temperature Derating',
    inputs: {
      scenarioId: 'high_temp_degradation',
      scenarioName: 'High Temperature Degradation',
      rotorMassKg: 110,
      operatingRpm: 2950,
      unbalanceMassGrams: 3.5,
      unbalanceRadiusMm: 140,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '7312_becbm',
      basicDynamicLoadC_kN: 104,
      useDirectLoadP: false,
      equivalentLoadP_kN: 15.0,
      staticRadialLoadN: 1400,
      axialLoadN: 600,
      lubricationCondition: 'poor',
      contaminationLevel: 'normal',
      reliabilityTarget: 0.95,
      machineType: 'fan',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 65,
      dampingRatio: 0.045,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 750,
      overhungLengthMm: 0,
      loadDistributionFactor: 0.55,
      bearingOperatingTempC: 105,
    },
    expectedOutputs: [
      { key: 'modifiedLifeL10mhHours', label: 'Modified Life L10mh', expected: '< 6,000 hrs', unit: 'hrs' },
      { key: 'bearingLifeStatus', label: 'Bearing Status', expected: 'Warning / Critical', unit: '' },
    ],
  },
  {
    id: 'validation_benchmark',
    name: 'Validation Benchmark: Ball Bearing (C/P = 8, 1800 RPM)',
    description: 'Reference ISO 281 test case: Ball bearing with C/P = 8.0 at 1800 RPM yielding exactly L10 = 512 million revolutions and ~4,740.7 hours.',
    industry: 'ISO 281 Benchmark Reference Standard',
    source: 'ISO 281 Benchmark Case Standard',
    inputs: {
      scenarioId: 'validation_benchmark',
      scenarioName: 'Validation Benchmark (C/P = 8)',
      rotorMassKg: 75,
      operatingRpm: 1800,
      unbalanceMassGrams: 1.5,
      unbalanceRadiusMm: 100,
      balanceGrade: 'G2.5',
      bearingType: 'ball',
      bearingCategorySelect: 'ball',
      bearingModelId: '6310',
      basicDynamicLoadC_kN: 65, // C = 65 kN
      useDirectLoadP: true,
      equivalentLoadP_kN: 8.125, // P = 8.125 kN -> C/P = 65/8.125 = 8.000 exactly
      staticRadialLoadN: 600,
      axialLoadN: 150,
      lubricationCondition: 'normal', // a_lube = 1.00
      contaminationLevel: 'clean', // a_contam = 1.00 (clean benchmark)
      reliabilityTarget: 0.90, // a1 = 1.00
      machineType: 'pump',
      machineClass: 'class_2_medium',
      rotorStiffnessKNmm: 50,
      dampingRatio: 0.05,
      bearingPosition: 'between_bearings',
      bearingSpanMm: 650,
      overhungLengthMm: 0,
      loadDistributionFactor: 0.50,
    },
    expectedOutputs: [
      { key: 'loadRatioCP', label: 'C/P Load Ratio', expected: '8.00', unit: 'x' },
      { key: 'basicLifeL10MillionRevs', label: 'Basic L10 (8³)', expected: '512 M revs', unit: 'M revs' },
      { key: 'basicLifeL10hHours', label: 'Basic Life L10h', expected: '4,741 hrs (~4740.7 hrs)', unit: 'hrs' },
      { key: 'iso10816Zone', label: 'Vibration Zone', expected: 'Zone A', unit: '' },
    ],
  },
];
