import { SealInputs } from '../types/seal';
import { ValidationPreset } from '../types/common';

export const SEAL_PRESETS: ValidationPreset<SealInputs>[] = [
  {
    id: 'api682_plan11_orifice_benchmark',
    name: 'Plan 11 with Orifice (Validation Benchmark)',
    description: 'API 682 benchmark calculation: d = 3.0 mm orifice, ΔP = 100 kPa (1 bar), ρ = 1000 kg/m³, Cd = 0.60 standard discharge flush recirculation.',
    industry: 'Refining & General Chemical',
    source: 'API 682 4th Ed Annex C / Hydraulic Benchmark',
    inputs: {
      planId: 'plan_11',
      sealSizeMm: 65,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 400,
      pumpDischargePressureKPag: 500, // deltaP = 100 kPa
      pumpSuctionPressureKPag: 200,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 45,
      processFluidType: 'water',
      fluidDensityKgM3: 1000,
      fluidSpecificHeatCp: 4.184,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.06,
      allowableFlushTempRiseC: 10,
      coolingWaterSupplyTempC: 30,
      coolingWaterFlowLpm: 15,
      coolerCapacityKW: 5,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 0,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.0,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
    expectedOutputs: [
      { key: 'actualOrificeFlowLpm', label: 'Orifice Flow (Cd=0.6, 3mm, 100kPa)', expected: '3.60 L/min', unit: 'L/min' },
      { key: 'sealFaceHeatGenKW', label: 'Seal Face Heat (Q_face)', expected: '~ 0.5 - 0.9 kW', unit: 'kW' },
      { key: 'status', label: 'Seal Status', expected: 'Safe (Normal)', unit: '' },
    ],
  },
  {
    id: 'api682_plan21_hot_water',
    name: 'Plan 21 Hot Water Service (HX Cooled)',
    description: 'Discharge recirculation through restriction orifice and heat exchanger for high-temperature hot water / light hydrocarbon service.',
    industry: 'Power Generation & Hydrocarbon Processing',
    source: 'API 682 Plan 21 Datasheet',
    inputs: {
      planId: 'plan_21',
      sealSizeMm: 65,
      shaftSpeedRpm: 2980,
      sealChamberPressureKPag: 600,
      pumpDischargePressureKPag: 2200,
      pumpSuctionPressureKPag: 250,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 130, // Hot water
      processFluidType: 'water',
      fluidDensityKgM3: 935,
      fluidSpecificHeatCp: 4.26,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.73,
      faceFrictionCoeff: 0.06,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 28,
      coolingWaterFlowLpm: 25,
      coolerCapacityKW: 12,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 12,
      accumulatorPrechargeKPag: 0,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.5,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
    expectedOutputs: [
      { key: 'sealChamberOperatingTempC', label: 'Chamber Operating Temp', expected: '< 55°C (Cooled)', unit: '°C' },
      { key: 'vaporPressureMarginKPa', label: 'Vapor Margin', expected: '> 500 kPa', unit: 'kPa' },
      { key: 'coolerDutyRequiredKW', label: 'Cooler Heat Duty', expected: '~ 2.0 - 4.5 kW', unit: 'kW' },
    ],
  },
  {
    id: 'api682_plan32_clean_external',
    name: 'Plan 32 Clean External Flush (Slurry Service)',
    description: 'External clean, compatible fluid injected into seal chamber at high pressure to isolate faces from abrasive mineral slurries.',
    industry: 'Mining, FGD Slurry & Chemical Processing',
    source: 'API 682 Plan 32 / Hydraulic Institute Guidelines',
    inputs: {
      planId: 'plan_32',
      sealSizeMm: 75,
      shaftSpeedRpm: 1780,
      sealChamberPressureKPag: 350,
      pumpDischargePressureKPag: 850,
      pumpSuctionPressureKPag: 100,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 60,
      processFluidType: 'crude_oil',
      fluidDensityKgM3: 998,
      fluidSpecificHeatCp: 4.184,
      faceMaterials: 'sic_vs_sic',
      balanceRatioK: 0.74,
      faceFrictionCoeff: 0.08,
      allowableFlushTempRiseC: 10,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 10,
      coolerCapacityKW: 4,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 10,
      accumulatorPrechargeKPag: 0,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 4.0,
      externalFlushPressureKPag: 550, // 200 kPa above chamber
      externalFlushFlowLpm: 12.0,
      quenchFluidType: 'water',
    },
    expectedOutputs: [
      { key: 'actualFlushFlowLpm', label: 'Injected External Flush', expected: '12.0 L/min', unit: 'L/min' },
      { key: 'vaporPressureMarginKPa', label: 'Vapor Margin', expected: '> 400 kPa', unit: 'kPa' },
      { key: 'status', label: 'API 682 Status', expected: 'Safe (Slurry Isolated)', unit: '' },
    ],
  },
  {
    id: 'api682_plan53b_pressurized_barrier',
    name: 'Plan 53B Pressurized Barrier (Bladder Accumulator)',
    description: 'Arrangement 3 dual pressurized seal with pre-charged bladder accumulator for toxic hydrocarbon or offshore pipeline pumping.',
    industry: 'Offshore Oil & Gas Pipelines',
    source: 'API 682 4th Ed Annex G System 53B',
    inputs: {
      planId: 'plan_53b',
      sealSizeMm: 75,
      shaftSpeedRpm: 2950,
      sealChamberPressureKPag: 1200,
      pumpDischargePressureKPag: 4500,
      pumpSuctionPressureKPag: 800,
      barrierBufferPressureKPag: 1500, // 300 kPa above chamber
      processFluidTempC: 70,
      processFluidType: 'crude_oil',
      fluidDensityKgM3: 840,
      fluidSpecificHeatCp: 2.15,
      faceMaterials: 'sic_vs_sic',
      balanceRatioK: 0.74,
      faceFrictionCoeff: 0.07,
      allowableFlushTempRiseC: 8,
      coolingWaterSupplyTempC: 30,
      coolingWaterFlowLpm: 18,
      coolerCapacityKW: 6,
      barrierFluid: 'iso_vg_5_synthetic',
      barrierFluidVolumeL: 20,
      accumulatorPrechargeKPag: 1100,
      pressureControlMethod: 'bladder_accumulator',
      flushOrificeDiameterMm: 3.5,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'nitrogen',
    },
    expectedOutputs: [
      { key: 'barrierPressureDifferentialKPa', label: 'Barrier Margin ΔP', expected: '300 kPa (Within Margin > 140)', unit: 'kPa' },
      { key: 'accumulatorMarginKPa', label: 'Accumulator Precharge Margin', expected: '400 kPa', unit: 'kPa' },
      { key: 'status', label: 'Seal Status', expected: 'Safe (Zero Emission)', unit: '' },
    ],
  },
  {
    id: 'api682_plan62_quench_service',
    name: 'Plan 62 Atmospheric Quench Service (Caustic / Steam)',
    description: 'External low-pressure steam or water quench applied on atmospheric side to prevent product crystallization, coking, or atmospheric icing.',
    industry: 'Petrochemical, Chlor-Alkali & Bitumen',
    source: 'API 682 Plan 62 Quench Guide',
    inputs: {
      planId: 'plan_62',
      sealSizeMm: 65,
      shaftSpeedRpm: 1480,
      sealChamberPressureKPag: 300,
      pumpDischargePressureKPag: 950,
      pumpSuctionPressureKPag: 120,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 85,
      processFluidType: 'caustic_soda',
      fluidDensityKgM3: 1150,
      fluidSpecificHeatCp: 3.8,
      faceMaterials: 'sic_vs_sic',
      balanceRatioK: 0.75,
      faceFrictionCoeff: 0.07,
      allowableFlushTempRiseC: 10,
      coolingWaterSupplyTempC: 25,
      coolingWaterFlowLpm: 10,
      coolerCapacityKW: 3,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 8,
      accumulatorPrechargeKPag: 0,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 3.2,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
    expectedOutputs: [
      { key: 'vaporPressureMarginKPa', label: 'Vapor Margin', expected: '> 300 kPa', unit: 'kPa' },
      { key: 'sealFaceHeatGenKW', label: 'Face Heat Gen', expected: '~ 0.4 - 0.7 kW', unit: 'kW' },
      { key: 'status', label: 'API 682 Status', expected: 'Safe (Quench Active)', unit: '' },
    ],
  },
  {
    id: 'api682_plan23_hot_bfw_boiler_feed',
    name: 'Plan 23 High-Temp Boiler Feedwater (Energy-Saving)',
    description: 'Energy-efficient closed-loop recirculation with internal pumping ring and dedicated heat exchanger for 160°C BFW.',
    industry: 'Supercritical Power & Industrial Steam',
    source: 'API 682 / HI Mechanical Seal Guide Plan 23',
    inputs: {
      planId: 'plan_23',
      sealSizeMm: 75,
      shaftSpeedRpm: 2980,
      sealChamberPressureKPag: 1200,
      pumpDischargePressureKPag: 5000,
      pumpSuctionPressureKPag: 800,
      barrierBufferPressureKPag: 0,
      processFluidTempC: 160,
      processFluidType: 'boiler_feedwater',
      fluidDensityKgM3: 907,
      fluidSpecificHeatCp: 4.34,
      faceMaterials: 'carbon_vs_sic',
      balanceRatioK: 0.72,
      faceFrictionCoeff: 0.05,
      allowableFlushTempRiseC: 10,
      coolingWaterSupplyTempC: 32,
      coolingWaterFlowLpm: 20,
      coolerCapacityKW: 8,
      barrierFluid: 'water_glycol_50_50',
      barrierFluidVolumeL: 10,
      accumulatorPrechargeKPag: 0,
      pressureControlMethod: 'fixed_n2_regulator',
      flushOrificeDiameterMm: 4.0,
      externalFlushPressureKPag: 0,
      externalFlushFlowLpm: 0,
      quenchFluidType: 'steam',
    },
    expectedOutputs: [
      { key: 'vaporPressureMarginKPa', label: 'Vapor Margin', expected: '> 700 kPa', unit: 'kPa' },
      { key: 'coolerDutyRequiredKW', label: 'Cooler Heat Duty', expected: '~ 1.5 - 2.8 kW', unit: 'kW' },
      { key: 'status', label: 'API 682 Status', expected: 'Safe', unit: '' },
    ],
  },
];
