import { SealPlanId } from '../types/seal';

export interface SealPlanMatrixRow {
  planId: SealPlanId;
  name: string;
  category: 'Single Seal (Internal)' | 'Single Seal (Cooling)' | 'Single Seal (Special)' | 'Dual Unpressurized' | 'Dual Pressurized' | 'Atmospheric Quench';
  flushSource: string;
  flushDestination: string;
  coolingMethod: string;
  pressurizationMethod: string;
  typicalApplication: string;
  mainRisk: string;
  recommendedMonitoring: string[];
  schematicSummary: string;
}

export const SEAL_PLAN_MATRIX: Record<SealPlanId, SealPlanMatrixRow> = {
  plan_11: {
    planId: 'plan_11',
    name: 'Plan 11',
    category: 'Single Seal (Internal)',
    flushSource: 'Pump discharge nozzle',
    flushDestination: 'Seal chamber (stuffing box)',
    coolingMethod: 'Continuous process fluid flow dissipation',
    pressurizationMethod: 'Pump discharge differential head',
    typicalApplication: 'General hydrocarbon and clean chemical service below 80°C (175°F); non-polymerizing clean fluids.',
    mainRisk: 'Orifice plugging resulting in complete loss of flush, rapid heat buildup, and face dry running; vaporization if margins are low.',
    recommendedMonitoring: [
      'Pressure transmitter upstream/downstream of orifice',
      'Seal flush line skin temperature indicator (TI)',
      'Periodic thermal imaging for orifice line blockage',
    ],
    schematicSummary: 'Discharge line → Restriction Orifice → Seal Chamber Port',
  },
  plan_13: {
    planId: 'plan_13',
    name: 'Plan 13',
    category: 'Single Seal (Internal)',
    flushSource: 'Seal chamber (stuffing box)',
    flushDestination: 'Pump suction nozzle',
    coolingMethod: 'Continuous venting flow through seal chamber to pump suction',
    pressurizationMethod: 'Seal chamber to suction pressure differential',
    typicalApplication: 'Vertical in-line pumps, self-venting horizontal pumps, fluids with moderate vapor pressure.',
    mainRisk: 'Reduced chamber pressure leading to premature fluid vaporization at seal faces if suction pressure is low.',
    recommendedMonitoring: [
      'Seal chamber pressure gauge',
      'Skin temperature on recirculation line to suction',
      'Flow indicator on return line',
    ],
    schematicSummary: 'Seal Chamber Port → Restriction Orifice → Pump Suction Line',
  },
  plan_21: {
    planId: 'plan_21',
    name: 'Plan 21',
    category: 'Single Seal (Cooling)',
    flushSource: 'Pump discharge nozzle',
    flushDestination: 'Seal chamber after passing through cooler',
    coolingMethod: 'Process-stream heat exchanger (water or air cooled)',
    pressurizationMethod: 'Pump discharge differential head',
    typicalApplication: 'Hot clean services, hot hydrocarbons, boiler feed water up to 150°C (300°F).',
    mainRisk: 'Cooler tube fouling or plugging from wax/coke, high cooling water heat duty demand, loss of cooling water causing sudden seal boiling.',
    recommendedMonitoring: [
      'Cooler inlet & outlet temperature transmitters (TIT)',
      'Cooling water supply flow switch',
      'Pressure differential indicator across cooler and orifice',
    ],
    schematicSummary: 'Discharge → Orifice → Heat Exchanger Cooler → Seal Chamber',
  },
  plan_23: {
    planId: 'plan_23',
    name: 'Plan 23',
    category: 'Single Seal (Cooling)',
    flushSource: 'Seal chamber outlet (driven by internal pumping ring)',
    flushDestination: 'Seal chamber inlet after passing through cooler',
    coolingMethod: 'Closed-loop dedicated heat exchanger (very high thermal efficiency)',
    pressurizationMethod: 'Shaft-mounted internal pumping ring (bidirectional or axial)',
    typicalApplication: 'Hot boiler feed water (BFW) > 150°C (300°F), hot hydrocarbons, district energy heating pumps.',
    mainRisk: 'Vapor pocket accumulation or piping resistance causing pumping ring stall; throat bushing wear allowing hot process ingress.',
    recommendedMonitoring: [
      'Seal flush cooler inlet and outlet temperatures',
      'High-point automatic air vent or manual vent valve',
      'Skin thermocouple on seal gland cavity',
    ],
    schematicSummary: 'Seal Chamber Out → Pumping Ring → Cooler → Seal Chamber In (Closed Loop)',
  },
  plan_31: {
    planId: 'plan_31',
    name: 'Plan 31',
    category: 'Single Seal (Special)',
    flushSource: 'Pump discharge through hydrocyclone separator',
    flushDestination: 'Clean overflow to seal chamber; dirty underflow to pump suction',
    coolingMethod: 'Continuous process fluid flow dissipation',
    pressurizationMethod: 'Pump discharge to suction differential head',
    typicalApplication: 'Dirty liquids with heavy abrasive solid particles (specific gravity > 2× liquid SG), sand slurries.',
    mainRisk: 'Cyclonic nozzle erosion, underflow nozzle plugging sending grit directly to seal faces, inadequate solid density difference.',
    recommendedMonitoring: [
      'Differential pressure across hydrocyclone separator',
      'Temperature sensors on both clean and underflow legs',
      'Periodic erosion ultrasonic wall thickness checks',
    ],
    schematicSummary: 'Discharge → Cyclone Separator → Clean to Chamber / Dirty to Suction',
  },
  plan_32: {
    planId: 'plan_32',
    name: 'Plan 32',
    category: 'Single Seal (Special)',
    flushSource: 'External clean, compatible liquid injection source',
    flushDestination: 'Seal chamber (flushes inward into pump through throat bushing)',
    coolingMethod: 'External flush fluid flow absorption',
    pressurizationMethod: 'External positive displacement pump or header (> P_chamber + 150 kPa)',
    typicalApplication: 'Severe abrasive slurries, polymerizing/coking fluids, paper stock, caustic chemicals.',
    mainRisk: 'Product contamination/dilution from external flush fluid, high operating cost of flush fluid, loss of external pressure.',
    recommendedMonitoring: [
      'External flush flow meter and low-flow interlock switch (FSL)',
      'Pressure differential transmitter (P_flush - P_chamber)',
      'Check valve integrity verification',
    ],
    schematicSummary: 'External Clean Source → Flow Control & Check Valve → Seal Chamber',
  },
  plan_52: {
    planId: 'plan_52',
    name: 'Plan 52',
    category: 'Dual Unpressurized',
    flushSource: 'Unpressurized buffer fluid reservoir pot (Arrangement 2)',
    flushDestination: 'Dual seal outer cavity and returns to buffer reservoir',
    coolingMethod: 'Thermosiphon loop or internal pumping ring through external reservoir & coil',
    pressurizationMethod: 'Atmospheric or vented to low-pressure flare/VRS (< P_chamber)',
    typicalApplication: 'Volatile organic compounds (VOC), light hydrocarbons, hazardous fluids where process leakage must be captured in flare.',
    mainRisk: 'Inner seal failure causing rapid reservoir pressure spike; buffer liquid contamination or vaporization in reservoir.',
    recommendedMonitoring: [
      'High level switch (LSH) and low level switch (LSL) on reservoir',
      'High pressure switch/transmitter (PSH) indicating primary seal breach',
      'Buffer reservoir temperature indicator',
    ],
    schematicSummary: 'Buffer Reservoir (Vented to Flare) ↔ Outer Seal Cavity (P_buffer < P_chamber)',
  },
  plan_53a: {
    planId: 'plan_53a',
    name: 'Plan 53A',
    category: 'Dual Pressurized',
    flushSource: 'Pressurized barrier fluid reservoir with nitrogen blanket (Arrangement 3)',
    flushDestination: 'Dual seal barrier cavity between inner and outer seals',
    coolingMethod: 'Circulation via internal pumping ring through external reservoir & cooling coil',
    pressurizationMethod: 'Regulated plant nitrogen supply (> P_chamber + 140 kPa minimum)',
    typicalApplication: 'Toxic, carcinogenic, lethal, sour gas, zero-emission process applications.',
    mainRisk: 'Nitrogen dissolution in barrier fluid leading to frothing/foaming; loss of N2 supply causing reverse seal pressurization.',
    recommendedMonitoring: [
      'Barrier pressure transmitter with low-pressure interlock (PSL)',
      'Low level switch (LSL) indicating barrier consumption',
      'High level switch (LSH) indicating process fluid reverse ingress',
    ],
    schematicSummary: 'N2 Blanket Supply → Barrier Reservoir Pot ↔ Dual Seal Cavity (P_bar > P_box)',
  },
  plan_53b: {
    planId: 'plan_53b',
    name: 'Plan 53B',
    category: 'Dual Pressurized',
    flushSource: 'Closed-loop bladder accumulator pre-charged with nitrogen (Arrangement 3)',
    flushDestination: 'Dual seal barrier cavity and air/water cooled heat exchanger',
    coolingMethod: 'External air finned cooler or shell & tube water heat exchanger',
    pressurizationMethod: 'Pre-charged elastomeric bladder accumulator (isolates N2 from barrier fluid)',
    typicalApplication: 'High-pressure offshore pipelines, remote un-manned sites, sour crude where N2 gas dissolution cannot be tolerated.',
    mainRisk: 'Elastomeric bladder rupture, temperature-dependent pressure swings, barrier volume depletion requiring periodic top-up pump.',
    recommendedMonitoring: [
      'Temperature-compensated pressure transmitter algorithm',
      'Pressure switch low (PSL) calibrated to minimum operating temp',
      'Accumulator barrier fluid replenishment volume log',
    ],
    schematicSummary: 'Bladder Accumulator + Air/Water Cooler ↔ Dual Seal Cavity',
  },
  plan_53c: {
    planId: 'plan_53c',
    name: 'Plan 53C',
    category: 'Dual Pressurized',
    flushSource: 'Closed-loop piston differential accumulator with reference line from seal chamber',
    flushDestination: 'Dual seal barrier cavity and cooling heat exchanger',
    coolingMethod: 'Pumping ring through air/water heat exchanger',
    pressurizationMethod: 'Piston area ratio multiplier (e.g. 1.15:1) tracking process fluctuations automatically',
    typicalApplication: 'Pumps with widely fluctuating suction/discharge pressure, subsea injection, multi-product loading.',
    mainRisk: 'Piston dynamic seal friction or dynamic seal hang-up, dirty process reference line plugging piston sense port.',
    recommendedMonitoring: [
      'Piston stroke position indicator / transmitter (ZIT)',
      'Differential pressure gauge (P_barrier - P_chamber)',
      'High/low piston stroke limit switches',
    ],
    schematicSummary: 'Stuffing Box Reference Line → Piston Multiplier → Dual Seal Cavity',
  },
  plan_54: {
    planId: 'plan_54',
    name: 'Plan 54',
    category: 'Dual Pressurized',
    flushSource: 'Dedicated external pressurized barrier fluid circulation skid (Arrangement 3)',
    flushDestination: 'Multiple dual mechanical seals across entire pump train',
    coolingMethod: 'Centralized heavy-duty heat exchangers, duplex filters, and dual pumps',
    pressurizationMethod: 'Motor-driven positive displacement barrier pump with relief regulator',
    typicalApplication: 'Critical refinery units, offshore platforms, multiple high-heat generating seals on shared skid.',
    mainRisk: 'Central skid power failure affecting all connected pumps simultaneously; filter clogging causing loss of circulation.',
    recommendedMonitoring: [
      'Skid supply pressure & return pressure transmitters',
      'Individual seal branch flow meters & differential gauges',
      'Duplex filter differential pressure switches (DPSH)',
    ],
    schematicSummary: 'Centralized Lube/Barrier Skid (Pumps + HX + Filters) ↔ Dual Mechanical Seals',
  },
  plan_62: {
    planId: 'plan_62',
    name: 'Plan 62',
    category: 'Atmospheric Quench',
    flushSource: 'External low-pressure steam, nitrogen, or clean water header',
    flushDestination: 'Atmospheric side of single seal (between seal gland and throttle bushing)',
    coolingMethod: 'Convective atmospheric cooling and barrier purge',
    pressurizationMethod: 'Low pressure quench supply (< 35 kPa / 5 psi) with open drain',
    typicalApplication: 'Caustic soda (prevents crystallization), hot bitumen/coke (steam quench), cold fluids (prevents icing).',
    mainRisk: 'Over-pressurizing quench cavity blowing out throttle bushing or lip seal, steam condensate washing into bearing housing.',
    recommendedMonitoring: [
      'Quench pressure regulator & needle flow control valve',
      'Drain line open sight flow indicator and collection pot',
      'Bearing housing seal deflector / labyrinth check',
    ],
    schematicSummary: 'Low-P Quench Header (Steam/N2/Water) → Atmospheric Seal Side → Controlled Drain',
  },
};
