/**
 * Central Legal, Safe-Harbor, and Non-Affiliation Declarations
 * 
 * CRITICAL POLICY:
 * This software is an independent educational, training, and simulation screening tool.
 * It is NOT affiliated with, sponsored by, approved by, certified by, or endorsed by
 * any international standards organization or society (including API, ISO, ASME, HI, AGMA).
 * All references to standards, codes, and acronyms are used strictly under nominative fair use
 * for technical identification, mathematical modeling, and educational benchmarking.
 */

export const LEGAL_SAFE_HARBOR_NOTICE =
  "Independent educational simulation and decision-support tool only. NOT affiliated with, endorsed by, certified by, sponsored by, or approved by the American Petroleum Institute (API), International Organization for Standardization (ISO), American Society of Mechanical Engineers (ASME), Hydraulic Institute (HI), American Gear Manufacturers Association (AGMA), or any international standards society or regulatory agency. Standards designations and numeric criteria are cited solely under nominative fair use for educational benchmarking against open published engineering literature. All physical machinery operations, modifications, and safety-critical decisions require certified OEM data sheets and formal review by a licensed Professional Engineer.";

export const STANDARDS_SAFE_DISCLAIMER_SHORT =
  "Independent educational tool. NOT affiliated with, approved by, or endorsed by API, ISO, ASME, HI, AGMA, or any standards society. Citations are for technical benchmarking only under nominative fair use.";

export const CERTIFICATE_DISCLAIMER_TEXT =
  "NON-AFFILIATION & INDEPENDENT BENCHMARK DECLARATION: This document is an automated simulation report generated by Mechanical Lab Pro, an independent computational modeling tool. This certificate is NOT issued by, approved by, endorsed by, or affiliated with API, ISO, ASME, HI, AGMA, or any standard-setting society. Benchmark limits are derived from open technical literature and are provided strictly for educational comparison and engineering screening. Operational compliance must be validated by certified equipment testing and licensed Professional Engineers.";

/**
 * Format a standard citation into safe, non-infringing benchmark terminology
 */
export function formatBenchmarkRef(standardCode: string): string {
  return `${standardCode} Reference Guideline`;
}

/**
 * Safe phrasing replacements
 */
export const SAFE_PHRASES = {
  compliant: "Within Reference Benchmark",
  nonCompliant: "Exceeds Benchmark Threshold",
  standard: "Industry Reference Guideline",
  certificateTitle: "Independent Technical Benchmark Certificate & Simulation Audit",
};
