import { SteamTurbineScenario } from '../types/steamTurbine';

export const STEAM_TURBINE_SCENARIOS: SteamTurbineScenario[] = [
  {
    id: 'api-612-condensing-bfw-drive',
    name: 'API 612 Multi-Stage Condensing BFW Pump Drive (Baseline)',
    category: 'normal',
    description: 'Special purpose 3,500 kW, 5,500 RPM condensing steam turbine driving a high-pressure Boiler Feed Water (BFW) pump in a power utility.',
    event: 'Normal steady-state rated load operation with adequate inlet superheat and surface condenser vacuum.',
    consequence: 'Optimal isentropic expansion (η_s = 78.5%), exhaust wetness controlled to 7.6% (well below 12% erosion limit).',
    recommendedAction: 'Maintain current condenser cooling water flow and boiler steam drum demister operation.',
    inputs: {
      turbineType: 'condensing',
      stageDesign: 'impulse_rateau',
      inletPressureBar: 42.0,
      inletTemperatureC: 410.0,
      exhaustPressureBar: 0.10, // ~28.5 inHg vacuum
      ratedPowerKw: 3500,
      ratedSpeedRpm: 5500,
      numberOfStages: 8,
      meanBladeDiameterMm: 620,
      lastStageBladeLengthMm: 180,
      governingMode: 'nozzle_governing',
      governorDroopPercent: 4.0,
      operatingSpeedRpm: 5500,
      throttleValveOpeningPercent: 92,
      firstCriticalSpeedRpm: 2600,
      secondCriticalSpeedRpm: 7200,
      bladeMaterial: 'martensitic_stainless_12cr',
      bladeNaturalFrequencyHz: 4800,
      nozzlePassFrequencyCount: 42,
      stelliteErosionShieldInstalled: true,
      thrustBearingPadTempC: 72,
      lubeOilInletPressureBar: 2.2,
      condenserVacuumKpa: 10.0,
      casingWarmUpDifferentialMm: 0.25,
    },
  },
  {
    id: 'severe-wetness-blade-erosion',
    name: 'Severe Exhaust Wetness & L-0 Blade Droplet Impingement Erosion',
    category: 'abnormal',
    description: 'Loss of boiler superheat or cooling water overcooling causes steam quality to drop, producing heavy liquid droplet nucleation and moisture exceeding 14%.',
    event: 'Boiler desuperheater valve stuck open drops inlet temperature to 290°C. Moisture in the last stage reaches 14.8%.',
    consequence: 'Liquid Droplet Impingement Erosion (LDIE) rapidly pits blade leading edges and erodes stellite brazing, causing high-cycle fatigue.',
    recommendedAction: 'Immediately restore boiler superheat temperature to > 380°C and check exhaust hood drain traps.',
    inputs: {
      turbineType: 'condensing',
      stageDesign: 'impulse_rateau',
      inletPressureBar: 42.0,
      inletTemperatureC: 285.0, // Low superheat!
      exhaustPressureBar: 0.08, // Very low exhaust pressure
      ratedPowerKw: 3500,
      ratedSpeedRpm: 5500,
      numberOfStages: 8,
      meanBladeDiameterMm: 620,
      lastStageBladeLengthMm: 220,
      governingMode: 'throttle_governing',
      governorDroopPercent: 4.0,
      operatingSpeedRpm: 5500,
      throttleValveOpeningPercent: 95,
      firstCriticalSpeedRpm: 2600,
      secondCriticalSpeedRpm: 7200,
      bladeMaterial: 'martensitic_stainless_12cr',
      bladeNaturalFrequencyHz: 4800,
      nozzlePassFrequencyCount: 42,
      stelliteErosionShieldInstalled: false, // No shield -> rapid erosion!
      thrustBearingPadTempC: 76,
      lubeOilInletPressureBar: 2.1,
      condenserVacuumKpa: 8.0,
      casingWarmUpDifferentialMm: 0.35,
    },
  },
  {
    id: 'lateral-critical-speed-dwell',
    name: 'Lateral Critical Speed Dwell & High Shaft Vibration',
    category: 'abnormal',
    description: 'Turbine operating near its 1st lateral rotor critical speed (2,600 RPM) violating the API 612 >= 15% separation margin.',
    event: 'Operator turned down pump flow, causing governor to throttle speed into 2,620 RPM dwell zone near critical frequency.',
    consequence: 'Shaft relative displacement spikes to 82 μm peak-to-peak (ISO 20816 Zone D trip threshold), risking bearing babbitt wipe.',
    recommendedAction: 'Rapidly ramp turbine through 2,300 - 2,900 RPM critical exclusion band and reset minimum governor governor floor.',
    inputs: {
      turbineType: 'condensing',
      stageDesign: 'impulse_rateau',
      inletPressureBar: 42.0,
      inletTemperatureC: 410.0,
      exhaustPressureBar: 0.12,
      ratedPowerKw: 1800,
      ratedSpeedRpm: 5500,
      numberOfStages: 8,
      meanBladeDiameterMm: 620,
      lastStageBladeLengthMm: 180,
      governingMode: 'throttle_governing',
      governorDroopPercent: 4.0,
      operatingSpeedRpm: 2620, // Near 1st critical (2,600 RPM)!
      throttleValveOpeningPercent: 55,
      firstCriticalSpeedRpm: 2600,
      secondCriticalSpeedRpm: 7200,
      bladeMaterial: 'martensitic_stainless_12cr',
      bladeNaturalFrequencyHz: 4800,
      nozzlePassFrequencyCount: 42,
      stelliteErosionShieldInstalled: true,
      thrustBearingPadTempC: 68,
      lubeOilInletPressureBar: 2.2,
      condenserVacuumKpa: 12.0,
      casingWarmUpDifferentialMm: 0.20,
    },
  },
  {
    id: 'nozzle-pass-blade-resonance',
    name: 'Stator Nozzle Pass Frequency (NPF) Blade High-Cycle Resonance',
    category: 'abnormal',
    description: 'Nozzle wake shedding frequency aligns with fundamental blade bending resonance on stage 7, causing HCF excitation.',
    event: 'Running at 5,450 RPM with 48 stator nozzles produces NPF = 4,360 Hz, within 1.5% of blade natural frequency (4,400 Hz).',
    consequence: 'Aerodynamic wake shock waves excite blade bending modes; risk of blade shroud cracking and catastrophic blade liberation.',
    recommendedAction: 'Shift operating speed setpoint away from 5,450 RPM and perform modal inspection of blade lacing wires.',
    inputs: {
      turbineType: 'condensing',
      stageDesign: 'reaction_parsons',
      inletPressureBar: 48.0,
      inletTemperatureC: 440.0,
      exhaustPressureBar: 0.15,
      ratedPowerKw: 4200,
      ratedSpeedRpm: 5500,
      numberOfStages: 10,
      meanBladeDiameterMm: 580,
      lastStageBladeLengthMm: 160,
      governingMode: 'nozzle_governing',
      governorDroopPercent: 3.5,
      operatingSpeedRpm: 5450, // NPF matches blade natural frequency!
      throttleValveOpeningPercent: 88,
      firstCriticalSpeedRpm: 2400,
      secondCriticalSpeedRpm: 7800,
      bladeMaterial: 'martensitic_stainless_12cr',
      bladeNaturalFrequencyHz: 4360, // Exactly matches 48 * (5450/60) = 4360 Hz!
      nozzlePassFrequencyCount: 48,
      stelliteErosionShieldInstalled: true,
      thrustBearingPadTempC: 84,
      lubeOilInletPressureBar: 2.4,
      condenserVacuumKpa: 15.0,
      casingWarmUpDifferentialMm: 0.40,
    },
  },
  {
    id: 'api-611-back-pressure-syngas-drive',
    name: 'API 611 Back-Pressure Turbine for Syngas Compressor Drive',
    category: 'normal',
    description: 'High-pressure 8,200 kW, 10,800 RPM back-pressure industrial turbine exhausting steam into the medium-pressure plant steam header (4.5 bar).',
    event: 'Continuous process steam header balancing; exhaust remains completely dry and superheated with zero moisture risk.',
    consequence: 'High thermal efficiency integration with chemical plant process heating; no condenser required.',
    recommendedAction: 'Monitor back-pressure header relief valves and reaction thrust bearing pad temperature.',
    inputs: {
      turbineType: 'back_pressure',
      stageDesign: 'impulse_rateau',
      inletPressureBar: 85.0,
      inletTemperatureC: 480.0,
      exhaustPressureBar: 4.5, // Exhausts to 4.5 bar header
      ratedPowerKw: 8200,
      ratedSpeedRpm: 10800,
      numberOfStages: 6,
      meanBladeDiameterMm: 420,
      lastStageBladeLengthMm: 95,
      governingMode: 'nozzle_governing',
      governorDroopPercent: 4.0,
      operatingSpeedRpm: 10800,
      throttleValveOpeningPercent: 90,
      firstCriticalSpeedRpm: 4800,
      secondCriticalSpeedRpm: 14500,
      bladeMaterial: 'nickel_alloy_inconel',
      bladeNaturalFrequencyHz: 8500,
      nozzlePassFrequencyCount: 36,
      stelliteErosionShieldInstalled: false, // Not needed, dry exhaust!
      thrustBearingPadTempC: 88,
      lubeOilInletPressureBar: 2.8,
      condenserVacuumKpa: 101.3,
      casingWarmUpDifferentialMm: 0.45,
    },
  },
  {
    id: 'emergency-overspeed-trip-event',
    name: 'Generator Load Rejection & Emergency Overspeed Trip Event',
    category: 'abnormal',
    description: 'Sudden breaker opening creates instantaneous electrical load dump, accelerating the turbine toward its 110% mechanical overspeed trip bolt.',
    event: 'Full electrical load trip; turbine speed accelerates through 6,120 RPM (exceeding 110% trip threshold of 6,050 RPM).',
    consequence: 'Centrifugal blade stress increases by 24%, emergency 2oo3 trip bolt fires to close quick-closing stop valve in < 0.25 seconds.',
    recommendedAction: 'Verify trip bolt actuation time, test valve seat tight shutoff, and perform overspeed trip test before re-latching.',
    inputs: {
      turbineType: 'condensing',
      stageDesign: 'impulse_curtis',
      inletPressureBar: 42.0,
      inletTemperatureC: 410.0,
      exhaustPressureBar: 0.12,
      ratedPowerKw: 3500,
      ratedSpeedRpm: 5500,
      numberOfStages: 6,
      meanBladeDiameterMm: 620,
      lastStageBladeLengthMm: 180,
      governingMode: 'throttle_governing',
      governorDroopPercent: 4.0,
      operatingSpeedRpm: 6150, // OVERSPEED TRIP TRIGGERED!
      throttleValveOpeningPercent: 95,
      firstCriticalSpeedRpm: 2600,
      secondCriticalSpeedRpm: 7200,
      bladeMaterial: 'martensitic_stainless_12cr',
      bladeNaturalFrequencyHz: 4800,
      nozzlePassFrequencyCount: 42,
      stelliteErosionShieldInstalled: true,
      thrustBearingPadTempC: 98,
      lubeOilInletPressureBar: 2.0,
      condenserVacuumKpa: 12.0,
      casingWarmUpDifferentialMm: 0.85,
    },
  },
];
