import { SimulatorDocSectionProps } from '../components/Shared/SimulatorDocSection';

export const SEAL_DOC_DATA: Omit<SimulatorDocSectionProps, 'simulatorId'> = {
  h1Title: 'API Mechanical Seal Flush Plan Simulator',
  summary:
    'Simulate API 682 single and dual mechanical seal flush piping plans (Plan 11, 13, 21, 23, 31, 32, 52, 53A, 53B, 53C, 54, 62), compute frictional face heat generation (kW), restriction orifice hydraulic flow rates, seal chamber temperature rise, and vapor suppression margins.',
  howItWorks: [
    'Seal Face Frictional Power Model: Calculates heat generated at sliding face contact interface (Q_face = f_fric · P_net · A_face · V_mean) based on shaft speed, balance ratio, and material pair (Carbon/SiC or SiC/SiC).',
    'Plan Hydraulic Routing & Pressure Differential: Determines differential pressure (ΔP) driving flush flow through piping, coolers, cyclone separators, and restriction orifices (e.g. Plan 11 discharge-to-box vs Plan 13 box-to-suction).',
    'Restriction Orifice Flow Solver: Solves orifice flow using API 682 discharge coefficient (Cd = 0.62) to determine volumetric flow rate (Q_flush) delivered to the seal cavity.',
    'Thermal Equilibrium & Vapor Suppression Margin: Computes steady-state seal chamber temperature (T_box = T_proc + Q_face / (ρ·Cp·Q_flush)) and verifies minimum 20°C (36°F) or 200 kPa margin above fluid boiling point.',
  ],
  inputs: [
    {
      name: 'API 682 Flush Plan Selection',
      symbol: 'Plan',
      unit: 'API Code',
      description: 'Piping arrangement: Plan 11 (Discharge to box), Plan 13 (Box to suction), Plan 23 (Pumping ring loop), Plan 52 (Unpressurized dual), Plan 53A (Pressurized dual barrier).',
    },
    {
      name: 'Process Fluid',
      symbol: 'Fluid',
      unit: 'Medium',
      description: 'Pumped process fluid defining specific heat (Cp), density (ρ), and vapor pressure curve (P_vap).',
    },
    {
      name: 'Shaft Diameter / Balance Diameter',
      symbol: 'D_shaft / D_bal',
      unit: 'mm or in',
      description: 'Mechanical seal size determining mean sliding velocity and hydraulic closing face area.',
    },
    {
      name: 'Shaft Speed',
      symbol: 'N',
      unit: 'RPM',
      description: 'Rotational speed of seal rotating ring (mean velocity V_mean = π · D_mean · N / 60).',
    },
    {
      name: 'Seal Chamber Pressure',
      symbol: 'P_box',
      unit: 'kPag or psig',
      description: 'Static pressure inside the stuffing box / seal gland acting on the outboard face closing area.',
    },
    {
      name: 'Pump Discharge Pressure',
      symbol: 'P_disch',
      unit: 'kPag or psig',
      description: 'Discharge casing pressure driving Plan 11, Plan 21, and Plan 31 bypass flush loops.',
    },
    {
      name: 'Restriction Orifice Bore Diameter',
      symbol: 'd_orifice',
      unit: 'mm or in',
      description: 'Standard API restriction orifice size (minimum 3.2 mm / 1/8" per API 682 §6.1.2.8).',
    },
    {
      name: 'Face Material Combination',
      symbol: 'Face Pair',
      unit: 'Materials',
      description: 'Mating seal faces (Carbon vs Reaction-Bonded SiC, Carbon vs Tungsten Carbide, or Sintered SiC vs Sintered SiC).',
    },
  ],
  outputs: [
    {
      name: 'Seal Face Frictional Heat Power',
      symbol: 'Q_face',
      unit: 'kW or BTU/hr',
      threshold: 'Energy to be removed',
      description: 'Thermal energy generated by boundary lubrication and shear friction at the sliding interface.',
    },
    {
      name: 'Actual Orifice Flush Flow Rate',
      symbol: 'Q_flush',
      unit: 'L/min or GPM',
      threshold: 'Q_flush ≥ Q_req (API 682)',
      description: 'Hydraulic flow rate delivered through the flush piping under operating differential pressure.',
    },
    {
      name: 'Required Flush Flow Rate',
      symbol: 'Q_req',
      unit: 'L/min or GPM',
      threshold: 'For ΔT_box ≤ 5°C to 10°C',
      description: 'Minimum flush flow required to absorb Q_face while limiting seal chamber temperature rise.',
    },
    {
      name: 'Seal Chamber Temperature',
      symbol: 'T_box',
      unit: '°C or °F',
      threshold: 'T_box < T_boil - 20°C',
      description: 'Steady-state operating temperature inside the seal cavity under flush cooling.',
    },
    {
      name: 'Vapor Suppression Margin',
      symbol: 'ΔP_vap / ΔT_sub',
      unit: 'kPa or °C margin',
      threshold: '≥ 200 kPa or ≥ 20°C margin',
      description: 'Margin between seal chamber pressure and fluid boiling point to prevent explosive face dry-running.',
    },
  ],
  equations: [
    {
      title: 'Seal Face Frictional Heat Generation (Q_face)',
      formula: 'Q_face = f_fric · P_net · A_face · V_mean',
      variables: 'f_fric = Coefficient of friction (0.07 to 0.12), P_net = Net closing contact pressure (Pa), A_face = Hydraulic face area (m²), V_mean = Mean sliding velocity (m/s). Result is in Watts (W) or kW.',
      standardRef: 'API 682 4th Ed Annex C',
    },
    {
      title: 'Required Flush Flow Rate for Temperature Rise (ΔT)',
      formula: 'Q_req = Q_face / (ρ · Cp · ΔT_allowed)',
      variables: 'Q_face = Face heat (W), ρ = Fluid density (kg/m³), Cp = Specific heat capacity (J/kg·°C), ΔT_allowed = Maximum allowable temperature rise (typically 5°C / 9°F).',
      standardRef: 'API 682 Annex C.2',
    },
    {
      title: 'Restriction Orifice Flow Rate (Q_ro)',
      formula: 'Q_ro = Cd · A_orifice · √(2 · ΔP / ρ)',
      variables: 'Cd = Orifice discharge coefficient (0.62 for sharp-edge orifice), A_orifice = Cross-sectional area of orifice bore (m²), ΔP = Differential pressure (P_disch - P_box in Pa), ρ = Density (kg/m³).',
      standardRef: 'API 682 §6.1.2.8 & ISO 21049',
    },
    {
      title: 'Vapor Pressure Suppression Margin',
      formula: 'Margin_vap = P_box - P_vap(T_box)',
      variables: 'P_box = Absolute seal chamber pressure (kPa abs), P_vap(T_box) = True fluid vapor pressure evaluated at operating seal chamber temperature (kPa abs). Standard requires ≥ 200 kPa (29 psi).',
      standardRef: 'API 682 §4.1.3 & Annex F',
    },
  ],
  standards: [
    {
      code: 'API Standard 682 4th Edition',
      title: 'Pumps - Shaft Sealing Systems for Centrifugal and Rotary Pumps',
      relevantSection: 'Clause 6 (Piping Plans), Annex C (Calculation of Flush Flow Rates), and Annex F (Mechanical Seal Selection)',
    },
    {
      code: 'ISO 21049:2004',
      title: 'Petroleum, petrochemical and natural gas industries - Shaft sealing systems for centrifugal and rotary pumps',
      relevantSection: 'Worldwide standard aligning with API 682 design practices and seal flush categorizations',
    },
    {
      code: 'API 610 12th Edition',
      title: 'Centrifugal Pumps for Petroleum, Petrochemical and Natural Gas Industries',
      relevantSection: 'Section 6.8 (Mechanical Shaft Seals and auxiliary piping connections)',
    },
  ],
  limitations: [
    'Assumes clean, single-phase flush fluid without high solids concentration; slurries require Plan 31 (cyclone) or Plan 32 (external clean flush).',
    'Plan 23 thermosiphon loop calculation assumes properly sized internal pumping ring (impeller/screw) providing at least 0.5 bar head.',
    'Plan 53A barrier fluid pressure must be maintained at least 1.4 bar (20 psi) above seal chamber pressure at all times.',
  ],
  exampleCalculation: {
    title: 'Benchmark Verification: 65 mm Plan 11 Orifice Sizing on Light Naphtha',
    scenario:
      'Evaluate seal face heat power, required flush flow, and orifice delivery for a 65 mm balance diameter seal rotating at 2950 RPM handling light hydrocarbon (ρ = 720 kg/m³, Cp = 2200 J/kg·K). Discharge pressure = 1800 kPag, seal chamber pressure = 400 kPag, with a standard 3.2 mm restriction orifice.',
    given: [
      { label: 'Shaft Speed N', value: '2950 RPM' },
      { label: 'Seal Balance Dia', value: '65.0 mm' },
      { label: 'Material Pair', value: 'Carbon vs Sintered SiC' },
      { label: 'Discharge Press P_d', value: '1800 kPag (18 bar)' },
      { label: 'Chamber Press P_box', value: '400 kPag (4 bar)' },
      { label: 'Pressure Drop ΔP', value: '1400 kPa (14 bar)' },
      { label: 'Orifice Diameter', value: '3.20 mm (1/8")' },
    ],
    steps: [
      {
        step: 'Mean Sliding Velocity (V_mean)',
        formula: 'V_mean = π · D_bal · N / 60',
        substitution: 'π · 0.065 m · 2950 RPM / 60',
        result: '10.04 m/s',
      },
      {
        step: 'Seal Face Heat Generation (Q_face)',
        formula: 'Q_face = f_fric · P_net · A_face · V_mean',
        substitution: '0.08 · (320,000 Pa) · (0.00045 m²) · 10.04 m/s',
        result: '1.16 kW (1,157 Watts)',
      },
      {
        step: 'Required Flush Flow for ΔT ≤ 5°C (Q_req)',
        formula: 'Q_req = Q_face / (ρ · Cp · ΔT)',
        substitution: '1157 W / (720 kg/m³ · 2200 J/kg·K · 5.0 K)',
        result: '8.76 × 10⁻⁵ m³/s (5.26 L/min)',
      },
      {
        step: 'Plan 11 Actual Orifice Flow Delivery (Q_ro)',
        formula: 'Q_ro = Cd · A_ro · √(2 · ΔP / ρ)',
        substitution: '0.62 · (π·0.0032²/4) · √(2 · 1,400,000 / 720)',
        result: '3.11 × 10⁻⁴ m³/s (18.66 L/min)',
      },
      {
        step: 'Seal Chamber Temperature Rise & Vapor Check',
        formula: 'ΔT_actual = Q_face / (ρ · Cp · Q_actual)',
        substitution: '1157 W / (720 · 2200 · 0.000311 m³/s)',
        result: 'ΔT = 1.41 °C (Vapor Margin = 320 kPa, Safe!)',
      },
    ],
    conclusion:
      'Standard 3.2 mm Plan 11 orifice delivers 18.66 L/min under 14 bar ΔP, which easily exceeds the minimum required 5.26 L/min. Seal chamber temperature rise is restricted to just 1.41°C, providing a robust 320 kPa vapor suppression margin to eliminate face dry-running.',
  },
  faqs: [
    {
      question: 'What is the purpose of API 682 mechanical seal flush plans?',
      answer:
        'Mechanical seal faces generate significant frictional heat (typically 0.5 to 4.0 kW) as they slide together at speeds up to 30 m/s. API 682 seal flush plans circulate liquid through the seal cavity to remove this frictional heat, flush away abrasive particulate matter, prevent fluid vaporization between the faces, and (in dual seal arrangements) contain hazardous emissions.',
    },
    {
      question: 'What is the difference between Plan 11 and Plan 53A?',
      answer:
        'Plan 11 is a single-seal arrangement that routes process fluid from pump discharge through a restriction orifice into the seal chamber and back into the pump. Plan 53A is a dual-pressurized seal arrangement where a barrier fluid reservoir is pressurized with nitrogen at 1.4 to 2.0 bar above seal chamber pressure, creating a clean fluid barrier that prevents any toxic, flammable, or volatile process fluid from escaping to the atmosphere.',
    },
    {
      question: 'Why does API 682 mandate a minimum 3.2 mm (1/8") orifice diameter?',
      answer:
        'Restriction orifices smaller than 3.2 mm (0.125 in) are prone to clogging by rust, pipe scale, or suspended solids in the process stream. If an orifice clogs, flush flow ceases immediately, causing the seal faces to overheat and vaporize within minutes.',
    },
    {
      question: 'When should Plan 23 be chosen over Plan 11 for hot water boiler feed services?',
      answer:
        'Plan 23 uses an internal pumping ring to circulate only the fluid inside the seal chamber through a closed-loop heat exchanger and back to the seal. Because it cools only the seal chamber volume rather than cooling continuous high-volume discharge flow (as Plan 21 would), Plan 23 dramatically reduces boiler thermal energy waste and cooler heat load by 80% to 90%.',
    },
  ],
  relatedTools: [
    {
      id: 'pump',
      title: 'Centrifugal Pump Cavitation & NPSH Simulator',
      description: 'Ensure adequate suction pressure and avoid cavitation-induced shaft vibration.',
      standard: 'API 610 / HI 9.6.1',
    },
    {
      id: 'rotor',
      title: 'Rotor Unbalance and Bearing Life Simulator',
      description: 'Evaluate shaft runout, 1X orbit whirl, and dynamic bearing support reliability.',
      standard: 'ISO 1940 / 281',
    },
    {
      id: 'pipe',
      title: 'Pipe Thermal Expansion and Stress Visualizer',
      description: 'Evaluate pipe thermal expansion and nozzle reaction loads to prevent seal misalignment.',
      standard: 'ASME B31.3',
    },
  ],
};
